"""Existing ideas already captured in the docs (source="existing")."""

PLAY = "PLAYABLE_GAME_CARDS.md"
FILE = "CONTENT_SYSTEM.md"

def i(id, title, mode, ages, vc, situations, oneLiner, sourceFile, duration=(3, 10), materials="none", tags=()):
    return {
        "id": id, "title": title, "source": "existing", "sourceFile": sourceFile,
        "mode": mode, "oneLiner": oneLiner,
        "ages": sorted(set(a for a in ages if a in ["3-4", "5-6", "7-8", "9-10"])),
        "videoCall": vc,
        "situations": sorted(set(s for s in situations if s in ["home", "outside", "travel", "waiting", "bedtime", "car", "restaurant", "virtual"])),
        "duration": [duration[0], duration[1]], "materials": materials,
        "tags": list(tags), "links": [], "photos": [], "videos": [],
    }

EXISTING = []

# ---------------- 36 conversation games (PLAYABLE_GAME_CARDS.md) ----------------
EXISTING += [
    i("talk_i_spy", "I Spy", "talk", ["3-4","5-6","7-8"], True, ["car","waiting","travel","restaurant","virtual"],
      "Choose an object; others guess it from colour and shape clues.", PLAY, (3,10), "none", ["observe","deduce"]),
    i("talk_alphabet_hunt", "Alphabet Hunt", "talk", ["5-6","7-8","9-10"], True, ["car","travel","waiting","virtual"],
      "Find the alphabet in order around you, cooperating to reach Z.", PLAY, (5,15), "none", ["observe","chain"]),
    i("talk_find_something", "Find Something That…", "talk", ["3-4","5-6","7-8"], True, ["anywhere","home","car","waiting","virtual"],
      "Everyone finds something matching a called-out property, from round to soft.", PLAY, (3,10), "none", ["observe","category"]),
    i("talk_twenty_questions", "Twenty Questions", "talk", ["5-6","7-8","9-10"], True, ["car","waiting","travel","virtual"],
      "One player holds a secret; together you get twenty yes-or-no questions.", PLAY, (3,15), "none", ["deduce","logic"]),
    i("talk_guess_number", "Guess the Number", "talk", ["5-6","7-8","9-10"], True, ["car","waiting","queue","virtual"],
      "Narrow a secret number with higher/lower clues.", PLAY, (3,10), "none", ["deduce","math"]),
    i("talk_family_guess_who", "Family Guess Who", "talk", ["4-6","5-6","7-8","9-10"], True, ["dinner","home","waiting"],
      "Think of a person the family knows; others ask yes/no questions to guess.", PLAY, (5,15), "none", ["deduce","connection"]),
    i("talk_secret_rule", "Secret Rule", "talk", ["7-8","9-10"], True, ["waiting","home","restaurant","virtual"],
      "Work out the leader's secret membership rule by proposing examples.", PLAY, (5,15), "none", ["deduce","pattern"]),
    i("talk_fort_unfortunately", "Fortunately, Unfortunately", "talk", ["5-6","7-8","9-10"], True, ["car","travel","bedtime","virtual"],
      "Build one story alternating 'Fortunately…' and 'Unfortunately…' lines.", PLAY, (3,10), "none", ["alternate","story"]),
    i("talk_pass_a_story", "Pass-a-Story", "talk", ["3-4","5-6","7-8","9-10"], True, ["car","bedtime","waiting","virtual"],
      "Each player adds one sentence to a shared story in a circle.", PLAY, (3,10), "none", ["alternate","story"]),
    i("talk_question_only_story", "Question-Only Story", "talk", ["7-8","9-10"], True, ["waiting","car","virtual"],
      "Tell a scene using only questions; statements get turned into questions.", PLAY, (5,10), "none", ["alternate","inhibit","story"]),
    i("talk_change_the_ending", "Change the Ending", "talk", ["5-6","7-8","9-10"], True, ["bedtime","home","virtual"],
      "Rewind a known story, change one decision, and invent what happens next.", PLAY, (5,10), "none", ["transform","story"]),
    i("talk_picnic", "I'm Going on a Picnic", "talk", ["4-6","5-6","7-8","9-10"], True, ["car","restaurant","travel","waiting","virtual"],
      "Repeat the growing list of picnic items and add one of your own.", PLAY, (3,10), "none", ["accumulate","memory"]),
    i("talk_packing_trunk", "Packing a Trunk", "talk", ["5-6","7-8","9-10"], True, ["travel","car","virtual"],
      "Pack an imaginary trunk: repeat the list, add an item, and give a reason.", PLAY, (5,15), "none", ["accumulate","memory"]),
    i("talk_sound_chain", "Sound Chain", "talk", ["3-4","5-6","7-8"], True, ["car","waiting","travel","virtual"],
      "Copy the sound sequence and add one new short sound each round.", PLAY, (3,10), "none", ["accumulate","rhythm"]),
    i("talk_movement_chain", "Movement Chain", "talk", ["3-4","5-6","7-8"], True, ["home","queue","waiting","virtual"],
      "Copy the movement sequence and add one movement that fits your space.", PLAY, (3,10), "none", ["accumulate","imitate","movement"]),
    i("talk_word_chain", "Word Chain", "talk", ["5-6","7-8","9-10"], True, ["car","dinner","travel","virtual"],
      "Each word begins with the last sound of the previous word.", PLAY, (3,10), "none", ["chain","language"]),
    i("talk_rhyme_time", "Rhyme Time", "talk", ["4-6","5-6","7-8"], True, ["car","bedtime","waiting","virtual"],
      "Take turns saying real or silly words that rhyme with a starter.", PLAY, (3,10), "none", ["rhyme","language"]),
    i("talk_chidiya_udd", "Chidiya Udd", "talk", ["3-4","5-6","7-8"], True, ["restaurant","home","waiting","virtual"],
      "Lift your finger when the named thing truly flies; keep it down if not.", PLAY, (3,10), "none", ["inhibit","movement","culture"]),
    i("talk_buzz_fuzz", "Buzz and Fuzz", "talk", ["7-8","9-10"], True, ["car","dinner","waiting","virtual"],
      "Count up, swapping multiples of three for 'buzz' and five for 'fuzz'.", PLAY, (5,15), "none", ["inhibit","math"]),
    i("talk_forbidden_word", "Forbidden Word", "talk", ["6-8","7-8","9-10"], True, ["dinner","car","home","virtual"],
      "Keep a conversation going without saying the forbidden word.", PLAY, (3,10), "none", ["inhibit","talk"]),
    i("talk_not_a_spoon", "This Is Not a Spoon", "talk", ["4-6","5-6","7-8","9-10"], True, ["restaurant","waiting","home","virtual"],
      "Pretend an ordinary object is something surprising and guess what it is.", PLAY, (5,15), "none", ["transform","improv"]),
    i("talk_silly_acronyms", "Silly Acronyms", "talk", ["7-8","9-10"], True, ["restaurant","queue","waiting","virtual"],
      "Invent a funny phrase using the letters of a visible word in order.", PLAY, (3,10), "none", ["transform","language","wordplay"]),
    i("talk_would_you_rather", "Would You Rather? (Family)", "talk", ["4-6","5-6","7-8","9-10"], True, ["restaurant","car","dinner","virtual"],
      "Pick between two playful options and explain why; passing is fine.", PLAY, (3,10), "none", ["reveal","reason"]),
    i("talk_two_truths_silly", "Two Truths and a Silly", "talk", ["5-6","7-8","9-10"], True, ["dinner","home","waiting","virtual"],
      "Share two true things and one playful invention; guess the invention.", PLAY, (5,10), "none", ["reveal","deduce"]),
    i("talk_pits_cherries", "Pits, Cherries, and Seeds", "talk", ["5-6","7-8","9-10"], True, ["dinner","bedtime","home"],
      "Share a hard part, a good part, and something you are hoping for.", PLAY, (5,10), "none", ["reveal","reflect"]),
    i("talk_things_good_at", "Things I'm Good At", "talk", ["4-6","5-6","7-8","9-10"], True, ["dinner","bedtime","home"],
      "Name something you are getting good at; someone adds when they noticed it.", PLAY, (5,10), "none", ["reveal","build","connection"]),
    i("talk_boredom_menu", "Boredom Menu", "talk", ["5-6","7-8","9-10"], True, ["home","waiting"],
      "Invent a menu of family things to do when bored: quick, quiet, and energetic.", PLAY, (5,15), "none", ["reveal","plan"]),
    i("talk_aao_milo", "Aao Milo Shilo Shalo", "talk", ["4-6","5-6","7-8","9-10"], True, ["waiting","home","virtual"],
      "Traditional clapping rhyme: face a partner and repeat a four-beat hand pattern.", PLAY, (3,10), "none", ["rhythm","clap","culture"]),
    i("talk_tongue_twister", "Tongue-Twister Ladder", "talk", ["5-6","7-8","9-10"], True, ["car","queue","waiting","virtual"],
      "Say a short tongue twister slowly, then climb three speeds.", PLAY, (3,10), "none", ["rhythm","speech"]),
    i("talk_finger_dance", "Finger Dance Party", "talk", ["3-4","5-6","7-8"], True, ["restaurant","waiting","home","virtual"],
      "Only your fingers dance: copy the four-count move and add your own.", PLAY, (3,10), "none", ["rhythm","movement","quiet"]),
    i("talk_air_drawing", "Air Drawing", "talk", ["3-4","5-6","7-8"], True, ["waiting","bedtime","restaurant","virtual"],
      "Draw a shape in the air with one finger; everyone guesses what it is.", PLAY, (3,10), "none", ["observe","draw","quiet"]),
]

# ---------------- Make (CONTENT_SYSTEM.md) ----------------
EXISTING += [
    i("act_shadow_doubles", "Shadow Doubles", "make", ["3-4","5-6","7-8"], False, ["home","outside"],
      "Trace the stretched shadow of a toy or hand, then invent what it becomes.", FILE, (5,15), "household", ["notice","transform","draw"]),
    i("act_wiggly_snake", "Wiggly Paper Snake", "make", ["5-6","7-8"], False, ["home"],
      "Cut and fold a paper snake that wiggles when you pull a strip.", FILE, (5,15), "household", ["craft","transform"]),
    i("act_tissue_bunny", "Tissue Twist Animal", "make", ["4-6","5-6","7-8"], False, ["home"],
      "Twist a tissue into a little bunny or animal.", FILE, (5,15), "household", ["craft","transform"]),
    i("act_paper_claw", "Paper Claw Costume", "make", ["5-6","7-8","9-10"], False, ["home"],
      "Fold paper claws to wear and play a gentle creature game.", FILE, (5,15), "household", ["craft","costume"]),
    i("act_returning_disk", "Returning Paper Disk", "make", ["7-8","9-10"], False, ["outside","home"],
      "Build a paper disk that curves back toward you.", FILE, (10,20), "household", ["craft","physics"]),
    i("act_cross_boomerang", "Cross Boomerang", "make", ["7-8","9-10"], False, ["outside"],
      "Fold a cross-shaped paper boomerang and test its flight.", FILE, (10,20), "household", ["craft","physics"]),
    i("act_jumping_balloon", "Jumping Balloon Toy", "make", ["5-6","7-8"], False, ["home"],
      "Assemble a balloon-string toy that jumps; adult-led with latex care.", FILE, (5,15), "special", ["craft","movement"]),
    i("act_found_flower_frame", "Found-Flower Frame", "make", ["4-6","5-6","7-8"], False, ["outside","home"],
      "Press fallen flowers or leaves into a paper frame and bouquet.", FILE, (5,15), "household", ["craft","nature"]),
    i("act_secret_gift_wrap", "Secret Gift Wrap", "make", ["6-8","7-8","9-10"], False, ["home"],
      "Wrap a small gift with clever, kid-designed reveal details.", FILE, (5,15), "household", ["craft","help"]),
    i("act_blow_paper_creature", "Blow-to-Move Paper Creature", "make", ["4-6","5-6","7-8"], False, ["home"],
      "Make a paper creature you move by blowing through your own straw.", FILE, (5,15), "household", ["craft","movement"]),
    i("act_color_collage_walk", "Color Collage Walk", "make", ["4-6","5-6","7-8"], False, ["outside","home"],
      "Collect safe found bits and arrange a color collage.", FILE, (10,20), "household", ["notice","craft","nature"]),
    i("act_one_sheet_bunny", "One-Sheet Bunny", "make", ["5-6","7-8"], False, ["home"],
      "Fold one sheet of paper into a standing bunny.", FILE, (5,15), "household", ["craft","origami"]),
    i("act_bat_fold", "Bat Fold", "make", ["5-6","7-8"], False, ["home","outside"],
      "Fold a paper bat and flutter it around a clear space.", FILE, (5,15), "household", ["craft","origami"]),
    i("act_family_flag", "Family Flag", "make", ["5-6","7-8","9-10"], False, ["home"],
      "Design and draw a flag that represents your whole family.", FILE, (10,20), "household", ["craft","identity"]),
    i("act_cardboard_marble", "Cardboard Marble Path", "make", ["6-8","7-8","9-10"], False, ["home"],
      "Build a marble run from cardboard and tape; test and remix it.", FILE, (10,25), "household", ["build","physics"]),
    i("act_sock_puppet", "Sock Puppet Interview", "make", ["4-6","5-6","7-8"], False, ["home"],
      "Make a sock puppet and have it interview a family member.", FILE, (5,15), "household", ["craft","performance","talk"]),
    i("act_fold_fly_lab", "Fold-and-Fly Lab", "make", ["6-8","7-8","9-10"], False, ["home","outside"],
      "Fold several paper planes and run a gentle flight experiment.", PLAY, (10,20), "household", ["craft","predict","physics"]),
    i("act_paper_chain_machine", "Paper Chain Machine", "make", ["4-6","5-6","7-8"], False, ["home"],
      "Work as a team to build the longest paper chain you can.", FILE, (10,20), "household", ["craft","cooperate"]),
    i("act_nature_crown", "Nature Crown", "make", ["4-6","5-6","7-8"], False, ["outside","home"],
      "Weave a crown from safe, found natural materials.", FILE, (10,20), "household", ["craft","nature"]),
    i("act_toy_shadow_city", "Toy Shadow City", "make", ["4-6","5-6","7-8"], False, ["home","bedtime"],
      "Arrange toys by a light to build a whole city of shadows.", FILE, (5,15), "household", ["notice","imagine","draw"]),
]

# ---------------- Move (CONTENT_SYSTEM.md) ----------------
EXISTING += [
    i("act_bus_stop_dance", "Family Bus Stop Dance", "move", ["4-6","5-6","7-8","9-10"], True, ["home","outside","virtual"],
      "Learn and perform a wacky family dance at the 'bus stop' reveal.", FILE, (5,15), "none", ["dance","perform","music"]),
    i("act_color_limb_callout", "Color Limb Callout", "move", ["3-4","5-6","7-8"], True, ["home","outside","virtual"],
      "A caller names a color; everyone touches something of that color with a limb.", FILE, (3,10), "none", ["movement","observe"]),
    i("act_sock_knockdown", "Sock Knockdown", "move", ["5-6","7-8","9-10"], False, ["home"],
      "Rolled socks knock down paper-cup targets; family shares six throws.", FILE, (5,15), "household", ["target","cooperate","movement"]),
    i("act_three_bottle_relay", "Three-Bottle Relay", "move", ["5-6","7-8","9-10"], False, ["home","outside"],
      "Fill and transfer between clean empty bottles in a cooperative relay.", FILE, (5,15), "household", ["movement","cooperate"]),
    i("act_mirror_hands", "Mirror Hands", "move", ["3-4","5-6","7-8","9-10"], True, ["home","waiting","virtual"],
      "Face a partner and mirror each other's hand and face movements.", FILE, (3,10), "none", ["imitate","movement","quiet"]),
    i("act_two_hand_dot", "Two-Hand Dot Trail", "move", ["5-6","7-8","9-10"], False, ["home"],
      "Draw a trail and cross it with two hands at once.", FILE, (3,10), "household", ["coordination","draw"]),
    i("act_listen_land", "Listen-and-Land", "move", ["4-6","5-6","7-8"], False, ["home","outside"],
      "Toss or step only when you hear the go-signal; a listening movement game.", FILE, (3,10), "none", ["movement","listen"]),
    i("act_home_obstacle_remix", "Home Obstacle Remix", "move", ["5-6","7-8","9-10"], False, ["home","outside"],
      "Build an obstacle course from pillows and chairs, then run it together.", FILE, (10,20), "household", ["movement","build"]),
    i("act_one_minute_juggle", "One-Minute Juggle Path", "move", ["7-8","9-10"], False, ["home"],
      "Practice a one-minute juggling or scarf-toss path without a mastery goal.", FILE, (10,20), "household", ["coordination","practice"]),
    i("act_slow_motion_leader", "Slow-Motion Leader", "move", ["3-4","5-6","7-8"], True, ["home","outside","virtual"],
      "One player leads big slow motions; everyone mirrors at the same pace.", FILE, (3,10), "none", ["imitate","movement"]),
    i("act_rhythm_copycat", "Rhythm Copycat", "move", ["3-4","5-6","7-8"], True, ["home","waiting","virtual"],
      "Clap or tap a rhythm and copy the pattern back and forth.", FILE, (3,10), "none", ["rhythm","imitate","music"]),
    i("act_floor_pattern", "Floor-Is-a-Pattern", "move", ["4-6","5-6","7-8"], False, ["home"],
      "Move across the floor following a made-up pattern of hops and steps.", FILE, (3,10), "none", ["movement","pattern"]),
    i("act_cup_transfer", "Cup Transfer Race", "move", ["4-6","5-6","7-8"], False, ["home"],
      "Transfer cups or small safe objects without dropping them.", FILE, (3,10), "household", ["coordination","cooperate"]),
    i("act_back_to_back_stand", "Back-to-Back Stand", "move", ["5-6","7-8","9-10"], False, ["home","outside"],
      "Two players lean back-to-back and stand up together without hands.", FILE, (3,10), "none", ["cooperate","balance"]),
    i("act_animal_movement_chain", "Animal Movement Chain", "move", ["3-4","5-6","7-8"], True, ["home","outside","virtual"],
      "Move across a space like a chosen animal, then chain the movements.", FILE, (3,10), "none", ["imitate","movement"]),
    i("act_freeze_explain", "Freeze-and-Explain", "move", ["4-6","5-6","7-8"], True, ["home","outside","virtual"],
      "Freeze in a pose and explain what you are pretending to be.", FILE, (3,10), "none", ["inhibit","improv","movement"]),
    i("act_hallway_curling", "Hallway Target Curling", "move", ["5-6","7-8","9-10"], False, ["home"],
      "Slide a soft puck toward a hallway target and see who lands closest.", FILE, (5,15), "household", ["target","coordination"]),
    i("act_grandparent_move_teach", "Grandparent Move-and-Teach", "move", ["4-6","5-6","7-8","9-10"], True, ["home","virtual"],
      "A grandparent leads an old dance or move; the family mirrors and learns it.", FILE, (5,15), "none", ["imitate","intergenerational","movement"]),
    i("act_seated_balloon_keepup", "Seated Balloon Keep-Up", "move", ["4-6","5-6","7-8"], False, ["home"],
      "Keep a balloon off the ground while staying seated together.", FILE, (5,15), "special", ["cooperate","movement","coordination"]),
    i("act_movement_dice", "Family Movement Dice", "move", ["4-6","5-6","7-8"], False, ["home"],
      "Roll a movement cube and everyone performs the action; cooperative target.", FILE, (5,15), "household", ["movement","improv"]),
]

# ---------------- Think (CONTENT_SYSTEM.md) ----------------
EXISTING += [
    i("act_reverse_forks", "Reverse the Forks", "think", ["7-8","9-10"], False, ["home"],
      "Move one object to reverse the fork arrangement in a set-up puzzle.", FILE, (3,10), "household", ["puzzle","logic"]),
    i("act_sound_sequence", "Sound Sequence", "think", ["4-6","5-6","7-8"], True, ["home","waiting","virtual"],
      "Remember and repeat a growing sequence of sounds with visual options.", FILE, (3,10), "none", ["memory","sequence","rhythm"]),
    i("act_mirror_dot_drawing", "Mirror Dot Drawing", "think", ["5-6","7-8","9-10"], False, ["home","waiting"],
      "Draw a mirrored copy of a dot pattern on the other side of a line.", FILE, (3,10), "household", ["draw","logic","coordination"]),
    i("act_modified_tic_tac_toe", "Modified Tic-Tac-Toe", "think", ["5-6","7-8","9-10"], False, ["home","waiting","restaurant"],
      "Change one rule of tic-tac-toe and discover the new winning strategy.", FILE, (3,10), "none", ["logic","remix","puzzle"]),
    i("act_which_rule_changed", "Which Rule Changed?", "think", ["5-6","7-8","9-10"], True, ["home","waiting","virtual"],
      "The leader changes one sorting rule; players spot what changed.", FILE, (3,10), "household", ["deduce","pattern"]),
    i("act_sorting_machine", "Household Sorting Machine", "think", ["3-4","5-6","7-8"], False, ["home"],
      "Be the sorting machine: sort mixed household objects by a chosen rule.", FILE, (3,10), "household", ["sort","category"]),
    i("act_human_algorithm", "Human Algorithm", "think", ["6-8","7-8","9-10"], False, ["home"],
      "Follow the family's own step-by-step 'program' to complete a tiny task.", FILE, (5,15), "none", ["sequence","logic"]),
    i("act_debug_instructions", "Debug My Instructions", "think", ["6-8","7-8","9-10"], True, ["home","virtual"],
      "The adult gives faulty instructions; the child finds the bug and fixes it.", FILE, (5,15), "none", ["logic","talk"]),
    i("act_pattern_under_cups", "Pattern Under Cups", "think", ["4-6","5-6","7-8"], False, ["home","waiting"],
      "Hide a pattern under cups and predict where each item is.", FILE, (3,10), "household", ["pattern","memory"]),
    i("act_mystery_sound", "Mystery Object by Sound", "think", ["3-4","5-6","7-8"], True, ["home","waiting","virtual"],
      "Guess a household object by the sound it makes behind a screen.", FILE, (3,10), "household", ["listen","deduce"]),
    i("act_color_photo_hunt", "Color Photo Hunt", "think", ["4-6","5-6","7-8"], False, ["outside","home"],
      "Find and photograph a list of colors around the house or yard.", FILE, (5,15), "special", ["observe","camera","sort"]),
    i("act_predict_paper_flight", "Predict the Paper Flight", "think", ["5-6","7-8","9-10"], False, ["home","outside"],
      "Predict how far or where a paper plane will land, then test it.", FILE, (5,15), "household", ["predict","physics"]),
    i("act_floating_pepper", "Floating Pepper Lab", "think", ["5-6","7-8","9-10"], False, ["home"],
      "Watch pepper scatter from water with a drop of soap; a tiny science demo.", FILE, (5,10), "household", ["experiment","science"]),
    i("act_sink_or_float", "Sink-or-Float Kitchen Set", "think", ["4-6","5-6","7-8"], False, ["home"],
      "Predict, then test, which kitchen objects sink or float.", FILE, (5,15), "household", ["predict","experiment","science"]),
    i("act_one_move_puzzle", "One-Move Puzzle", "think", ["7-8","9-10"], False, ["home","waiting","restaurant"],
      "Rearrange objects so exactly one move fixes the puzzle.", FILE, (3,10), "household", ["puzzle","logic"]),
    i("act_memory_tray", "Memory Tray", "think", ["4-6","5-6","7-8"], False, ["home"],
      "Look at a tray of objects, then recall them after they are covered.", FILE, (3,10), "household", ["memory","observe"]),
    i("act_build_remix_teach", "Build, Remix, Teach", "think", ["5-6","7-8","9-10"], False, ["home"],
      "Build something, change one rule, then teach it back to the adult.", FILE, (5,15), "household", ["build","remix","teach-back"]),
    i("act_opposite_hand_drawing", "Opposite-Hand Drawing", "think", ["5-6","7-8","9-10"], False, ["home","waiting"],
      "Draw a simple picture using the hand you do not usually use.", FILE, (3,10), "household", ["draw","coordination"]),
    i("act_shape_detective", "Shape Detective", "think", ["3-4","5-6","7-8"], False, ["home","outside","waiting","restaurant"],
      "Spot and name the shapes hiding all around the room.", FILE, (3,10), "none", ["observe","pattern"]),
    i("act_secret_rule", "Secret Rule (Think)", "think", ["7-8","9-10"], True, ["home","waiting","virtual"],
      "Deduce the hidden sorting or membership rule from examples.", FILE, (5,15), "none", ["deduce","pattern","logic"]),
]

# ---------------- Talk extra (distinct; CONTENT_SYSTEM.md) ----------------
EXISTING += [
    i("talk_alphabet_conversation", "Alphabet Conversation", "talk", ["5-6","7-8","9-10"], True, ["home","car","dinner","virtual"],
      "Take turns speaking in sentences that each start with the next letter.", FILE, (5,10), "none", ["chain","language","talk"]),
    i("talk_sentence_charades", "Sentence Charades", "talk", ["5-6","7-8","9-10"], True, ["home","waiting","virtual"],
      "Act out a whole sentence, word by word, for others to guess.", FILE, (5,15), "none", ["perform","improv","imitate"]),
    i("talk_seven_real_questions", "Seven Real Questions", "talk", ["5-6","7-8","9-10"], True, ["dinner","car","bedtime","virtual"],
      "Ask someone seven genuinely curious questions and really listen.", FILE, (5,15), "none", ["reveal","connection","talk"]),
    i("talk_good_deed_draft", "Good-Deed Draft", "talk", ["5-6","7-8","9-10"], True, ["dinner","home","bedtime"],
      "Draft one small kind act for someone and plan how to do it.", FILE, (5,10), "none", ["plan","connection","help"]),
    i("talk_adjective_faces", "Adjective Faces", "talk", ["4-6","5-6","7-8"], True, ["home","waiting","virtual"],
      "Make an exaggerated face for a word like 'proud' or 'silly'.", PLAY, (3,10), "none", ["perform","imitate","emotion"]),
    i("talk_describe_and_draw", "Describe-and-Draw", "talk", ["5-6","7-8","9-10"], True, ["home","virtual"],
      "One person describes, the other draws from the description alone.", PLAY, (5,15), "household", ["improv","listen","draw"]),
    i("talk_finish_my_story", "Finish My Story", "talk", ["4-6","5-6","7-8"], True, ["car","bedtime","virtual"],
      "The adult starts a story and the child invents several different endings.", PLAY, (3,10), "none", ["story","improv"]),
    i("talk_restaurant_reporter", "Restaurant Reporter", "talk", ["4-6","5-6","7-8"], False, ["restaurant","waiting"],
      "Be the quiet reporter and describe the scene like a news story.", FILE, (3,10), "none", ["observe","talk","perform"]),
    i("talk_toy_press_conference", "Toy Press Conference", "talk", ["4-6","5-6","7-8"], True, ["home","virtual"],
      "A beloved toy holds a press conference; the family asks it questions.", PLAY, (5,15), "household", ["improv","perform","talk"]),
    i("talk_what_grownups_know", "What Should Grown-Ups Know?", "talk", ["5-6","7-8","9-10"], True, ["dinner","bedtime","virtual"],
      "Give grown-ups one thing you wish they understood better.", PLAY, (5,10), "none", ["reveal","reflect","connection"]),
    i("talk_memory_by_color", "Memory by Color", "talk", ["4-6","5-6","7-8"], True, ["car","bedtime","virtual"],
      "Recall a color, then the best memory that color brings to mind.", FILE, (3,10), "none", ["memory","reveal"]),
    i("talk_compliment_detective", "Compliment Detective", "talk", ["4-6","5-6","7-8","9-10"], True, ["dinner","home","virtual"],
      "Notice and share one specific, true thing you admire about someone.", PLAY, (5,10), "none", ["reveal","connection","build"]),
    i("talk_one_minute_family_news", "One-Minute Family News", "talk", ["5-6","7-8","9-10"], True, ["home","dinner","virtual"],
      "Broadcast a one-minute news roundup of the family's latest headlines.", PLAY, (3,10), "none", ["perform","talk","story"]),
    i("talk_question_jar", "The Question Jar Without a Jar", "talk", ["4-6","5-6","7-8","9-10"], True, ["dinner","car","waiting","virtual"],
      "Pick a question from the family's mental question jar and answer it.", PLAY, (5,15), "none", ["reveal","talk","connection"]),
]

# ---------------- Help (CONTENT_SYSTEM.md) ----------------
EXISTING += [
    i("help_laundry_match", "Laundry Match Team", "help", ["3-4","5-6","7-8"], False, ["home"],
      "Fold and sort laundry together as a matching team.", FILE, (5,15), "household", ["sort","help","cooperate"]),
    i("help_fold_teach", "Fold-and-Teach", "help", ["5-6","7-8","9-10"], False, ["home"],
      "Learn one fold, then teach it back to the adult or a toy.", FILE, (5,15), "household", ["teach-back","help"]),
    i("help_order_table", "Order for the Table", "help", ["4-6","5-6","7-8"], False, ["restaurant","home"],
      "With adult support, order for the family at a restaurant.", FILE, (10,20), "none", ["help","talk","independence"]),
    i("help_jacket_flip", "Jacket Flip", "help", ["3-4","5-6","7-8"], False, ["home"],
      "Practice the coat-flip trick to put on a jacket independently.", FILE, (3,5), "household", ["independence","help"]),
    i("help_gift_wrap_partner", "Gift-Wrap Partner", "help", ["5-6","7-8","9-10"], False, ["home"],
      "Partner up to wrap a gift: one measures and cuts, one tapes.", FILE, (10,20), "household", ["help","craft","cooperate"]),
    i("help_flower_finder", "Flower Finder Bouquet", "help", ["4-6","5-6","7-8"], False, ["outside","home"],
      "Gather safe, fallen petals and arrange a thoughtful bouquet.", FILE, (10,20), "household", ["help","nature","craft"]),
    i("help_set_table_pattern", "Set-the-Table Pattern", "help", ["3-4","5-6","7-8"], False, ["home"],
      "Set the table following a simple place-setting pattern.", FILE, (3,10), "household", ["help","sort","pattern"]),
    i("help_snack_assembly", "Snack Assembly Line", "help", ["3-4","5-6","7-8"], False, ["home"],
      "Build a snack on an assembly line, each person adding one part.", FILE, (3,10), "household", ["help","sequence","cooperate"]),
    i("help_grocery_color_hunt", "Grocery Color Hunt", "help", ["3-4","5-6","7-8"], False, ["home","travel"],
      "Find and match grocery items by color while putting them away.", FILE, (5,15), "household", ["sort","observe","help"]),
    i("help_toy_repair", "Toy Repair Inspector", "help", ["5-6","7-8","9-10"], False, ["home"],
      "Inspect a toy, find what needs fixing, and work out how to help.", FILE, (5,15), "household", ["help","think","solve"]),
    i("help_sock_sorting", "Sock Sorting Speed Round", "help", ["4-6","5-6","7-8"], False, ["home"],
      "Race (gently) to match and sort all the socks.", FILE, (3,10), "household", ["sort","help","cooperate"]),
    i("help_water_right_amount", "Water the Right Amount", "help", ["4-6","5-6","7-8"], False, ["home","outside"],
      "Learn how much water each plant needs and water it together.", FILE, (5,10), "household", ["help","care","measure"]),
    i("help_pack_outing_bag", "Pack the Outing Bag", "help", ["4-6","5-6","7-8"], False, ["home","travel"],
      "Plan and pack the bag for your next outing together.", FILE, (5,15), "household", ["help","plan"]),
    i("help_wipe_notice", "Wipe-and-Notice", "help", ["3-4","5-6","7-8"], False, ["home"],
      "Wipe a surface and notice what changed as it became clean.", FILE, (3,10), "household", ["help","observe"]),
    i("help_pick_clothes", "Pick Tomorrow's Clothes", "help", ["3-4","5-6","7-8"], False, ["home","bedtime"],
      "Choose tomorrow's outfit by weather and by favorite colors.", FILE, (3,10), "household", ["help","plan","independence"]),
    i("help_thank_you_delivery", "Thank-You Delivery", "help", ["4-6","5-6","7-8"], False, ["home"],
      "Deliver a small thank-you to someone who helped the family.", FILE, (5,15), "household", ["help","connection","talk"]),
    i("help_family_lost_found", "Family Lost-and-Found", "help", ["3-4","5-6","7-8"], False, ["home"],
      "Run a family lost-and-found and reunite misplaced items.", FILE, (5,15), "household", ["help","sort","solve"]),
    i("help_measure_recipe", "Measure the Recipe", "help", ["5-6","7-8","9-10"], False, ["home"],
      "Measure and count ingredients while following a simple recipe.", FILE, (10,25), "household", ["help","measure","math"]),
    i("help_quiet_cleanup", "Quiet Cleanup Mission", "help", ["3-4","5-6","7-8"], False, ["home"],
      "Finish cleanup as a quiet, low-energy cooperative mission.", FILE, (3,10), "household", ["help","cooperate"]),
    i("help_teach_household_skill", "Teach a Household Skill", "help", ["5-6","7-8","9-10"], False, ["home"],
      "The child teaches the adult one household skill they know.", FILE, (5,15), "household", ["teach-back","help","independence"]),
]

# ---------------- Perform (CONTENT_SYSTEM.md) ----------------
EXISTING += [
    i("perf_penetrating_palm", "Penetrating Palm", "perform", ["5-6","7-8","9-10"], True, ["home","virtual"],
      "Perform a simple 'penetrating palm' hand illusion and explain the misdirection.", FILE, (5,15), "none", ["magic","perform"]),
    i("perf_growing_thumb", "Growing Thumb Illusion", "perform", ["5-6","7-8","9-10"], True, ["home","virtual"],
      "Master the growing-thumb optical illusion and present it.", FILE, (5,15), "none", ["magic","perform"]),
    i("perf_missing_finger", "Missing Finger Trick", "perform", ["5-6","7-8","9-10"], True, ["home","virtual"],
      "Perform the classic missing-finger trick for the family.", FILE, (5,15), "none", ["magic","perform"]),
    i("perf_rubber_band_escape", "Rubber-Band Escape", "perform", ["7-8","9-10"], True, ["home","virtual"],
      "Learn a rubber-band escape and present it in a mini show.", FILE, (5,15), "household", ["magic","perform"]),
    i("perf_adjective_face_off", "Adjective Face-Off", "perform", ["5-6","7-8","9-10"], True, ["home","dinner","virtual"],
      "Two players deliver the same line with wildly different emotions.", FILE, (5,15), "none", ["perform","improv","imitate"]),
    i("perf_one_minute_talent", "One-Minute Family Talent", "perform", ["4-6","5-6","7-8","9-10"], True, ["home","dinner","virtual"],
      "Each person presents a one-minute talent; everyone applauds.", FILE, (5,15), "none", ["perform","show"]),
    i("perf_teach_back_toy", "Teach Back to a Toy", "perform", ["3-4","5-6","7-8"], True, ["home","virtual"],
      "Explain or demonstrate a skill to a favorite toy audience.", FILE, (5,10), "household", ["teach-back","perform","talk"]),
    i("perf_no_words_restaurant", "No-Words Restaurant", "perform", ["5-6","7-8","9-10"], False, ["restaurant"],
      "Order and interact using only gestures at a quiet table.", FILE, (5,15), "none", ["perform","improv"]),
    i("perf_sync_finger_wave", "Synchronous Finger Wave", "perform", ["5-6","7-8","9-10"], True, ["home","virtual"],
      "Coordinate a finger 'wave' with a partner in sync.", FILE, (3,10), "none", ["coordination","perform","movement"]),
    i("perf_mini_magic_show", "Mini Magic Show", "perform", ["5-6","7-8","9-10"], True, ["home","virtual"],
      "Rehearse two no-prep tricks and present a mini magic show.", FILE, (10,20), "none", ["magic","perform","show"]),
    i("perf_sound_effect_story", "Sound-Effect Story", "perform", ["4-6","5-6","7-8","9-10"], True, ["home","car","virtual"],
      "Tell a story while everyone adds live sound effects with voice and body.", FILE, (5,15), "none", ["story","sound","perform"]),
    i("perf_dance_other_decade", "Dance from Another Decade", "perform", ["5-6","7-8","9-10"], True, ["home","virtual"],
      "Learn a simple dance step from another decade and teach it.", FILE, (5,15), "none", ["dance","intergenerational","movement"]),
    i("perf_reverse_roles", "Reverse Roles", "perform", ["4-6","5-6","7-8"], True, ["home","virtual"],
      "Swap roles for a minute: the child 'leads' and the adult follows.", FILE, (3,10), "none", ["improv","performance","role-play"]),
    i("perf_three_prop_charades", "Three-Prop Charades", "perform", ["5-6","7-8","9-10"], True, ["home","restaurant","virtual"],
      "Act out a scenario using only three chosen props or gestures.", FILE, (5,15), "household", ["improv","perform"]),
    i("perf_family_news_broadcast", "Family News Broadcast", "perform", ["4-6","5-6","7-8","9-10"], True, ["home","virtual"],
      "Stage a short newscast about the family's made-up headlines.", FILE, (5,15), "none", ["perform","talk","story"]),
    i("perf_slowest_race_announcer", "Slowest Race Announcer", "perform", ["4-6","5-6","7-8"], True, ["home","outside","virtual"],
      "Race to be slowest while an announcer comments dramatically.", FILE, (3,10), "none", ["movement","perform","talk"]),
    i("perf_mystery_voice", "Mystery Voice", "perform", ["4-6","5-6","7-8"], True, ["home","waiting","virtual"],
      "Speak in a disguised or silly voice; everyone guesses who it is.", FILE, (3,10), "none", ["sound","perform","deduce"]),
    i("perf_copy_my_hands", "Copy My Hands", "perform", ["3-4","5-6","7-8"], True, ["home","waiting","virtual"],
      "Lead a slow hand routine; everyone mirrors and leads in turn.", FILE, (3,10), "none", ["imitate","coordination","quiet"]),
    i("perf_trick_explanation", "Trick Explanation Challenge", "perform", ["7-8","9-10"], True, ["home","virtual"],
      "Explain a trick's misdirection so clearly a younger child can follow.", FILE, (5,15), "none", ["magic","teach-back","talk"]),
    i("perf_grandparent_signature", "Grandparent's Signature Skill", "perform", ["4-6","5-6","7-8","9-10"], True, ["home","virtual"],
      "Invite a grandparent to teach a signature skill and perform it together.", FILE, (10,20), "none", ["intergenerational","perform","teach-back"]),
]
