"""How-to-play cards for the 50 brand-new ideas."""
def c(**kw):
    return {k: v for k, v in kw.items() if v}

CARDS = {
    "new_emotion_charades": c(
        say="Act out a feeling with your face and body only—no words. Whoever guesses right picks the next emotion!",
        steps="One player secretly picks a feeling and acts it out silently; everyone guesses. Then the actor can add a tiny moment that goes with it.",
        turns="The correct guesser chooses the next emotion.",
        end="After everyone has had a turn acting.",
        easier="Give three choices to guess from.",
        harder="Act two emotions in one silent scene.",
        coop="Every guess is welcome; no right or wrong answers.",
        recovery="If nobody guesses, the actor adds one more exaggerated face.",
    ),
    "new_yes_and_story": c(
        say="Let's build a story where every turn starts 'Yes, and…'. Whatever I say, you accept and add something new.",
        steps="Start a sentence; each next player replies 'Yes, and…' and adds to it, so the story grows without anyone blocking it.",
        turns="One 'Yes, and…' line per person, in a circle.",
        end="After two rounds each or when the story finds a fun ending.",
        easier="The adult starts and offers a new idea each turn.",
        harder="Without 'but' or 'no' in any line.",
        recovery="If a turn stalls, offer a wild detail to accept.",
    ),
    "new_word_at_a_time": c(
        say="We tell a story one word at a time. I say one word, you say the next… let's see where it goes!",
        steps="Take turns adding a single word to build a sentence, then a story; the first word after a period starts a new sentence.",
        turns="One word per person, going around.",
        end="After a set number of words or when the story closes.",
        easier="Just build one silly sentence.",
        harder="Every sentence must include a color word.",
        coop="It only works if everyone listens and adds.",
        recovery="A strange word becomes a plot twist.",
    ),
    "new_sound_detective": c(
        say="Close your eyes. What do you think made that sound?",
        steps="One player makes a sound (voice, hands, or a safe object); everyone guesses the source before the maker reveals.",
        turns="The correct guesser gets to make the next sound.",
        end="After everyone has made a sound.",
        easier="Make obvious sounds like clapping or a bell.",
        harder="Make a surprising sound with a mix of objects.",
        recovery="If no one guesses, give one clue about where the sound came from.",
    ),
    "new_guess_hummed_song": c(
        say="I'll hum a song we all know—no words. Can you name it?",
        steps="One player hums a familiar tune; the others try to name it first; then the guesser hums the next.",
        turns="Each player gets to hum one song.",
        end="After everyone has hummed or the family has had enough.",
        easier="Hum a very famous song very slowly.",
        harder="Hum only the rhythm, no tune.",
        coop="Keep to songs the whole family knows—no one is tested.",
        recovery="Add a tap of the beat if no one can place it.",
    ),
    "new_story_builder": c(
        say="Pick a character, a place, a problem, and a tool—now let's build a story from them!",
        steps="Choose one of each from a make-believe list (or count fingers to 'roll'), then weave them into a story together.",
        turns="Each player adds one story beat in turn.",
        end="After everyone has added a beat and the story resolves.",
        easier="The adult supplies all four elements first.",
        harder="The final beat must use every element.",
        recovery="A silly combination is the fun—embrace it.",
    ),
    "new_family_rules_draft": c(
        say="Let's write one brand-new family rule—it can be silly. Then we vote!",
        steps="Brainstorm one playful rule, phrase it together, vote to accept, and decide how long it lasts (an hour, a day, a week).",
        turns="Each person proposes a rule; everyone votes.",
        end="When a rule is accepted and named.",
        easier="Adult writes it; child decorates it.",
        harder="The rule must solve a tiny real annoyance.",
        coop="Voting together keeps it fair.",
        recovery="A rejected rule is just 'vetoed' and someone else proposes next.",
    ),
    "new_emoji_story": c(
        say="Here's my emoji sequence: 🐢🚀🎈. Tell me the story it suggests!",
        steps="Line up 3–5 emojis (on a screen or drawn on paper), then tell the story they suggest; the next player reorders them for a fresh tale.",
        turns="Each player lays out one sequence for another to read.",
        end="After everyone has told and set one story.",
        easier="Two emojis only.",
        harder="Use a sequence that must end on the same emoji it begins.",
        recovery="If the story stalls, add one more emoji to help.",
    ),
    "new_three_clues": c(
        say="I'm thinking of something. Three clues… guess after the third!",
        steps="One player describes a person, place, or object with exactly three clues, then reveals; others guess after one or three clues.",
        turns="The correct guesser gives the next three clues.",
        end="After everyone has given a turn.",
        easier="Clues are color, shape, and use.",
        harder="Clues must get vaguer, not easier.",
        coop="Multiple guesses are welcomed.",
        recovery="A too-hard mystery gets one extra clue after the reveal.",
    ),
    "new_family_interview_show": c(
        say="Welcome to the show! I'm your host, and tonight we're interviewing… a family member. First question!",
        steps="The child hosts a talk show, interviewing a family member with curious questions, while others are the studio audience.",
        turns="The host swaps after a few questions.",
        end="After each willing player has been host and guest.",
        easier="Use a question starter list.",
        harder="The guest must answer in character as their favorite animal.",
        coop="Big, friendly applause after every answer.",
        recovery="If the guest is stuck, the audience suggests a question.",
    ),
    "new_guess_my_favorite": c(
        say="I'm thinking of my favorite thing this week. Ask yes-or-no questions to find it!",
        steps="One player picks a favorite; others ask yes/no questions to narrow it down and guess.",
        turns="The correct guesser picks the next favorite.",
        end="After everyone has had a turn, or the food arrives.",
        easier="Give a free clue after three questions.",
        harder="Limit to ten questions.",
        coop="Everyone helps ask the smartest questions.",
        recovery="If it's too hard, the picker reveals the category.",
    ),
    "new_name_acrostic": c(
        say="Let's make a poem from your name. 'M' is for… 'A' is for…?",
        steps="Take a name and write one line starting with each letter, describing the person or a made-up adventure; read it aloud.",
        turns="Each player writes an acrostic for someone in the family.",
        end="When each name has a poem.",
        easier="Adult writes the line, child picks the words.",
        harder="Every line must rhyme with the last.",
        coop="Read the finished poems aloud to each other.",
        recovery="A tricky letter can stand for a silly made-up word.",
    ),
    "new_backwards_day": c(
        say="For one minute, let's answer things backwards—'I brush my teeth before breakfast'? That's backwards-day style!",
        steps="Answer everyday questions back-to-front for a short round, treating every reverse answer as the silliest possible truth.",
        turns="Each player gets a turn to call a 'backwards question.'",
        end="After one minute or one full round.",
        easier="Just name one thing backwards.",
        harder="Act out the backwards answer too.",
        coop="Everyone shares the silly rule together.",
        recovery="A mixed-up answer is simply the most backwards one.",
    ),
    "new_virtual_scavenger": c(
        say="On the count of three, find something 'round' in your house—ready? Go!",
        steps="On a video call, a list of items is read; each home finds them in its own rooms and holds up the first to find.",
        turns="Each player (or home) reads one item; all homes race gently.",
        end="After everyone has found an item, or the list is done.",
        easier="Three easy items like 'something blue.'",
        harder="Harder items like 'something that rolls but isn't a ball.'",
        coop="It's a fun race, not a tournament—everyone cheers.",
        recovery="If an item is missing, pick a new one together.",
        safety="Only reachable, safe items; no climbing.",
    ),
    "new_show_tell_mystery": c(
        say="I've got a mystery object. I'll describe it without naming it—guess what it is before I show my screen!",
        steps="One player hides an object, describes its color, feel, and use without naming it, then reveals it to the camera.",
        turns="Each player hides one object and reveals it.",
        end="After everyone has had a turn.",
        easier="Describe just one clue.",
        harder="Only describe how it feels, never its use.",
        coop="Guessing together is the fun.",
        recovery="A stumped team gets one more clue from the hider.",
    ),
    "new_guess_my_drawing": c(
        say="I'm drawing something—watch me draw it, then guess what it is!",
        steps="One player draws an object and holds it up to the camera (or shows the paper) while others guess; swap drawers each round.",
        turns="The correct guesser draws next.",
        end="After everyone has drawn once.",
        easier="Draw a simple shape or animal.",
        harder="Draw only the outline of a detailed scene.",
        coop="Cheer each drawing, messy or neat.",
        recovery="If it's too hard, the drawer adds one label letter.",
    ),
    "new_mirror_yoga": c(
        say="Follow my stretch on screen—breathe in as you reach up, out as you settle. Let's mirror each other.",
        steps="A far family member leads a simple stretch or pose on camera; everyone mirrors and breathes together; then swap leader.",
        turns="Each player leads a few gentle poses.",
        end="After everyone has led, or a calm five minutes.",
        easier="Just seated arm reaches.",
        harder="Hold each pose for three breaths.",
        coop="Moving together builds connection even apart.",
        recovery="Go at your own pace; no one is corrected for form.",
        safety="Gentle moves only; stop on discomfort.",
    ),
    "new_recipe_together": c(
        say="We're both making the same snack right now. Measure the flour—three, two, one, add!",
        steps="Both households make the same simple no-cook snack at the same time on the call, counting ingredients together and comparing results.",
        turns="Each side measures or adds one ingredient in turn.",
        end="When both snacks are ready to taste.",
        easier="A no-measure snack like arranging fruit.",
        harder="Count out exact numbers and check they match.",
        coop="You cook 'side by side' even across screens.",
        recovery="A spilled ingredient is part of cooking together.",
        safety="Adult supervises any cutting or appliances.",
    ),
    "new_read_together": c(
        say="Let's read our book together. You take this page; I'll take the next!",
        steps="Take turns reading pages of a picture book aloud across the call, with one holding the book to camera or both having a copy.",
        turns="Alternate pages or characters' voices.",
        end="After a chapter or a set number of pages.",
        easier="The adult reads; the child turns the pages.",
        harder="Each reader voices a different character.",
        coop="Reading together makes it a shared story.",
        recovery="A long book can pause and continue another day.",
    ),
    "new_finger_puppet_show": c(
        say="We've made finger puppets—now for their grand performance for Grandma on screen!",
        steps="Make quick paper finger puppets, then stage a tiny show for a far grandparent who watches and applauds on camera.",
        turns="Each puppeteer gets one short scene.",
        end="After each puppet has performed and taken a bow.",
        easier="Use hands on a wall for a shadow puppet instead.",
        harder="Add a simple 'stage' made of a cardboard frame.",
        coop="The far grandparent is the delighted audience.",
        recovery="A dropped puppet is a funny stage accident.",
    ),
    "new_virtual_playdate_qa": c(
        say="Let's do a playdate check-in! I'll ask a fun question—everyone answers, then the next person asks.",
        steps="Use a short list of friendship questions (favorite game, best day this week) to keep cousins or friends connected on a call.",
        turns="The last answerer asks the next question.",
        end="After a set number of questions or when interest fades.",
        easier="Start with 'what's your favorite color?'",
        harder="Ask a question that starts with the letter of your name.",
        coop="It keeps the connection going, question by question.",
        recovery="A quiet friend gets a 'pass' or a second chance.",
    ),
    "new_photo_story_share": c(
        say="Pick one photo and tell us its story—where were we, and what happened next?",
        steps="Each player chooses one family photo, holds it up on the call (or around the table), and tells the story behind it.",
        turns="Each player shares one photo per round.",
        end="After everyone has told one story.",
        easier="Just say one true sentence about the photo.",
        harder="Make the story a funny 'news report' about the moment.",
        coop="Listening carefully is the real game.",
        recovery="A forgotten detail becomes a shared guessing game.",
    ),
    "new_virtual_freeze_dance": c(
        say="Dance to our song! When the music stops, freeze like a statue—let's see who wobbles.",
        steps="Everyone dances in their own home to a shared song, then freezes when the music pauses; a wobble just earns a silly freeze.",
        turns="Take turns picking the song.",
        end="After two or three songs.",
        easier="Freeze into any shape.",
        harder="Freeze into a specific shape the caller names.",
        coop="No one sits out—wobbles are funny, not losses.",
        recovery="If you move during freeze, everyone laughs and refreezes.",
    ),
    "new_guess_my_room": c(
        say="I'm going to slowly show you my room—guess where I am and what you can see!",
        steps="One player slowly pans the camera around their room; others guess the place and describe what they spot.",
        turns="Each player tours their own room.",
        end="After everyone has gone or a set time.",
        easier="Just guess one object on screen.",
        harder="Guess which room of the house it is and why.",
        coop="Everyone contributes their observations.",
        recovery="A blurry camera is an 'artistic' tour.",
    ),
    "new_together_blocks": c(
        say="Let's both build the same thing right now—a tower with one door. Ready? Build!",
        steps="Both players build the same simple shape with their own blocks at the same time, checking in on camera, then compare the two.",
        turns="Each player names what to build next round.",
        end="When both builds are done and compared.",
        easier="Build a simple tower of the same height.",
        harder="Build an identical design without peeking at the other for the last minute.",
        coop="Building 'together' even in different rooms.",
        recovery="Different results are a fun comparison, not a contest.",
    ),
    "new_cloud_dough": c(
        say="Let's mix flour and oil into squishy dough and see what shapes we can form.",
        setup="A bowl, flour, cooking oil, and a tray.",
        steps="Adult mixes flour and oil into a moldable dough; the child presses, forms, and stamps shapes in it.",
        turns="Each child shapes their own batch.",
        end="When the dough is formed and tidied away.",
        easier="Adult mixes; child just plays.",
        harder="Make a specific shape with your hands.",
        coop="Making the batch is a shared step.",
        recovery="Too dry? Add a drop of oil. Too sticky? Add flour.",
        safety="Adult mixes; enforced no-tasting; wash hands after.",
    ),
    "new_calm_bottle": c(
        say="Let's make a glitter bottle to shake and watch when you need a calm moment.",
        setup="A clear bottle, water, glitter (or fine glitter glue), and a tight-sealing lid.",
        steps="Fill the bottle with water and glitter, seal it tightly, then shake and watch the glitter settle slowly.",
        turns="Each child adds a color of glitter.",
        end="When every calm bottle is sealed and tested.",
        easier="Just water and two colors.",
        harder="Add a slow-settling secret (a touch of glue).",
        recovery="Leak? Reseal the lid over a sink.",
        safety="Adult seals the lid; supervise the bottle.",
    ),
    "new_pasta_necklace": c(
        say="Let's thread pasta tubes onto a string, sorting by color as we go, to make a necklace!",
        setup="Large pasta tubes, a length of string (or yarn with a taped tip), and a tray.",
        steps="Thread pasta pieces onto the string, sorting colors in a pattern the child chooses, then tie it into a necklace.",
        turns="Each child creates their own section or necklace.",
        end="When each necklace is threaded and tied.",
        easier="Adult holds the string; child threads.",
        harder="Follow a color pattern (red, red, white).",
        recovery="A dropped piece is simply picked back up.",
        safety="Supervise small hands and the string; adult prevents tasting.",
    ),
    "new_leaf_rubbings": c(
        say="Put this leaf under your paper and rub the crayon over it—watch the veins appear!",
        setup="Leaves, paper, and crayons (peeled).",
        steps="Place a leaf under paper and rub the crayon's side over it to reveal its pattern; try different leaves and coins.",
        turns="Each child collects and rubs their own leaves.",
        end="When each paper is covered with rubbing art.",
        easier="Adult holds the leaf steady.",
        harder="Arrange leaves into a shape first, then rub around it.",
        coop="Collecting leaves together is half the fun.",
        recovery="A smudged rubbing just becomes a creative blend.",
        safety="Only safe, clean fallen leaves.",
    ),
    "new_paper_plate_clock": c(
        say="Let's turn this plate into a clock—then you can set the time and tell me what it says!",
        setup="A paper plate, markers, and a split pin (or brad).",
        steps="Draw numbers around a paper plate, attach two hands with the pin, then practise setting and reading times.",
        turns="Each child sets a time for the family to read.",
        end="When each child has set and read a few times.",
        easier="Only the hour hand and o'clock times.",
        harder="Add minute hand and half-past times.",
        coop="Solve the 'what time is it' puzzle together.",
        recovery="A wrong setting is a chance to count the clock again.",
        safety="Adult handles the pin.",
    ),
    "new_handprint_art": c(
        say="Let's stamp our handprints and turn them into a family garden—who's each flower?",
        setup="Washable paint, paper, and a well-covered surface.",
        steps="Paint each person's hand and stamp prints into a family tree or garden scene, then label who is who.",
        turns="Each person adds their handprint.",
        end="When the art has everyone's print and a title.",
        easier="Adult paints the hand; child stamps.",
        harder="Add a petal or leaf decoration on each print.",
        coop="Every handprint together makes the whole picture.",
        recovery="A smeared print is just 'abstract art.'",
        safety="Washable paint; adult preps the surface.",
    ),
    "new_cardboard_fort": c(
        say="Let's build a fort (or a rocket!) from these boxes. Where should the door go?",
        setup="Cardboard boxes, tape, and scissors.",
        steps="Pile and tape boxes into a fort or rocket, add a door and windows, then decorate and play inside.",
        turns="Each child designs one part (door, window, flag).",
        end="When the structure stands and is decorated.",
        easier="Build a simple cave from two boxes.",
        harder="Add an interior 'room' or a curtain door.",
        coop="It's a shared build—everyone's part matters.",
        recovery="A tipping wall is re-taped and braced.",
        safety="Adult handles cutting; keep boxes dry and clean.",
    ),
    "new_soft_target_toss": c(
        say="Let's toss soft beanbags into the target and add our scores together as a family!",
        setup="Soft items (beanbags, rolled socks) and a target (a basket or marked line).",
        steps="Toss soft objects into a target from a gentle line, adding everyone's scores into one family total.",
        turns="Each player tosses; the family adds the running score.",
        end="When you hit a family goal or a set number of throws.",
        easier="A big, close target.",
        harder="Stand a bit farther, or toss under one leg.",
        coop="It's one shared score—you beat the target together.",
        recovery="A miss just leaves more throws for the team.",
        safety="Soft objects only, below shoulder height, clear space.",
    ),
    "new_animal_freeze_dance": c(
        say="Dance like a bear! … Freeze! Now a bunny! … Freeze!",
        steps="Dance as a named animal, then freeze in that animal's pose when the music stops; pick a new animal each round.",
        turns="Each child picks the next animal.",
        end="After a few animals or songs.",
        easier="Do the same animal twice.",
        harder="Freeze in a two-animal 'scene' with a partner.",
        coop="Everyone dances every round—no one sits out.",
        recovery="A wobble mid-freeze is a new 'animal twitch.'",
        safety="Clear space; adjust for small rooms.",
    ),
    "new_body_letter_shapes": c(
        say="Make the letter 'T' with your body! Now 'O.' Can you do a whole word?",
        steps="Shape your whole body into letters or numbers for others to guess; a partner can join to make two-letter words.",
        turns="Each player poses a letter; others guess.",
        end="After everyone has posed, or you've spelled a word.",
        easier="Single big letters.",
        harder="Two players spell a word together.",
        coop="Working together on a word is the fun part.",
        recovery="A tricky letter becomes a group brainstorm.",
    ),
    "new_simon_says_remix": c(
        say="Simon says touch your nose… touch your toes! (Oops, I didn't say Simon says!)",
        steps="Play Simon Says as a team; if someone follows a cue without 'Simon says,' everyone laughs and resets together—nobody sits out.",
        turns="Each player takes a turn being Simon.",
        end="After everyone has been Simon.",
        easier="Very slow cues.",
        harder="Two quick cues in a row.",
        coop="Following together is the goal—slips are funny, not losses.",
        recovery="A slip is a shared laugh and a fresh start.",
    ),
    "new_hallway_balance": c(
        say="Let's walk the line like a balance beam—arms out, one foot in front of the other!",
        setup="A line of tape on the floor (or an imagined line).",
        steps="Walk a straight taped line like a balance beam, forward then backward, arms out; try carrying a soft item.",
        turns="Each player takes a turn; everyone watches and cheers.",
        end="After everyone has crossed both ways.",
        easier="Walk slowly, no carrying.",
        harder="Walk backward, or carry a soft ball.",
        coop="Cheering every crossing is the rule.",
        recovery="A wobble-off is a laugh and a re-step.",
        safety="Level, clear floor.",
    ),
    "new_house_sortathon": c(
        say="Let's sort this big mixed pile by color! Then by size. What rule next?",
        setup="A mixed pile of safe household objects (blocks, toys, spoons).",
        steps="Sort a safe pile by a chosen rule (color, size, use), then pick a new rule and re-sort.",
        turns="Each child names the next sorting rule.",
        end="After three different sorts.",
        easier="Sort by one obvious rule.",
        harder="Sort by two rules at once (small and red).",
        coop="Agree on the rule together first.",
        recovery="A disputed object gets a family vote.",
    ),
    "new_guess_the_count": c(
        say="How many crackers do you think are in this jar? Everyone guesses, then we count!",
        setup="A clear jar or handful of small, countable safe items.",
        steps="Look at a jar or handful, estimate the count, write your guess, then count together to see who came closest.",
        turns="Each player guesses and takes a counting turn.",
        end="When the real count is revealed.",
        easier="Guess more/less than ten.",
        harder="Guess the exact number, then regroup by fives to check.",
        coop="Counting together builds the answer.",
        recovery="A wild guess is just part of the fun of estimating.",
    ),
    "new_paper_fold_fractions": c(
        say="Fold this paper in half—now count the two equal parts. Fold again: how many now?",
        setup="A sheet of paper per person.",
        steps="Fold a paper into halves, then fourths, then eighths, counting the equal parts each time and labeling them.",
        turns="Each child folds and counts their own, comparing with the family.",
        end="When everyone has folded to eighths and labeled them.",
        easier="Just halves and fourths.",
        harder="Shade one eighth and name it.",
        coop="Practice folding together on one shared sheet first.",
        recovery="An uneven fold is a good chance to talk about 'equal.'",
    ),
    "new_build_a_bridge": c(
        say="Build a bridge between these two books that holds the most pennies—then make it stronger!",
        setup="Paper or card, two raised supports (books), and small weights (coins or blocks).",
        steps="Build a paper bridge across a gap, test how many weights it holds, then change one design detail to hold more.",
        turns="Each player proposes and tests one design change.",
        end="When the bridge holds a satisfying load.",
        easier="Adult builds a base; child tests the load.",
        harder="Experiment with folds, layers, and arches.",
        coop="Improving the bridge together to beat your own record.",
        recovery="A collapse is data—look at where it bent.",
        safety="Small weights only; nothing heavy dropped.",
    ),
    "new_pattern_memory": c(
        say="Watch my color pattern: red, blue, red. Now you copy it—and add one!",
        setup="Colored cards, blocks, or hand gestures.",
        steps="Show a short color/gesture sequence, have the family copy it, then add one step each round to grow it.",
        turns="Each person adds one step.",
        end="When the sequence gets too long or two rounds are done.",
        easier="Two-step patterns.",
        harder="Swap colors half-way, or reverse the order.",
        coop="The group works together to rebuild the sequence.",
        recovery="If lost, reveal the sequence once more, then repeat.",
    ),
    "new_make_bed_mission": c(
        say="Secret mission: make this bed a team! You pull your corner, I'll smooth mine—go!",
        setup="The bed's own sheets, blanket, and pillows.",
        steps="Make the bed cooperatively, each person claiming one part (a corner, a pillow, smoothing the blanket).",
        turns="Swap parts each time until everyone has done each job.",
        end="When the bed is made and admired.",
        easier="Just pull up the blanket together.",
        harder="Time yourselves as a team and try to beat the family record.",
        coop="It's a mission completed together, not a chore assigned.",
        recovery="A lumpy spot is smoothed by the next person.",
    ),
    "new_grocery_put_away": c(
        say="Let's sort the groceries—cold things to the fridge, pantry things to the shelf. Where does this go?",
        setup="The shopping, ready to put away.",
        steps="Sort groceries into categories (cold, pantry, fruit) as you put them away, counting each group.",
        turns="Each child claims a category to put away.",
        end="When everything is away and counted.",
        easier="Just put away the fruit.",
        harder="Sort a mixed bag before you open it.",
        coop="Everyone finishes the shared put-away.",
        recovery="A misplaced item is easily re-homed.",
        safety="Adult handles glass jars and heavy items.",
    ),
    "new_plant_pet_helper": c(
        say="This week you're the helper for our plant (or pet). Let's check what it needs today.",
        setup="A safe plant-care or pet-care job (watering, fresh water, a gentle brush).",
        steps="Take on one caring job for the week with adult check-in, decide the right amount, and do it gently each day.",
        turns="Each child can pick their own job for the week.",
        end="Through the week, with a check-in each day.",
        easier="The adult checks first; child does one step.",
        harder="Keep a tiny daily 'did we care' tick sheet.",
        coop="Caring is a family responsibility, shared.",
        recovery="A forgotten day is just a fresh start tomorrow.",
        safety="Adult supervises pet contact and any water/lifting.",
    ),
    "new_thank_you_card": c(
        say="Who helped us this week? Let's make them a thank-you card and decorate it.",
        setup="Paper, markers, and anything to decorate.",
        steps="Choose who to thank, draw or write a short message, decorate it, and deliver or send it.",
        turns="Each child makes their own card or adds to one.",
        end="When every card is made and sent.",
        easier="A drawn picture with your name.",
        harder="Write your own words and a P.S.",
        coop="Delivering together makes it a family act.",
        recovery="A smudged message is fixed with a fresh card.",
    ),
    "new_snack_server": c(
        say="You're our snack server! Please hand everyone their snack and ask if they need anything else.",
        setup="Snacks already prepared by an adult.",
        steps="Be the polite snack server: hand each family member their snack and ask if they need anything, like a real helper.",
        turns="Each child takes a turn as server.",
        end="When everyone is served.",
        easier="Serve just one person.",
        harder="Ask each person what they'd like, then deliver it.",
        coop="Serving others kindly IS the job.",
        recovery="A dropped snack is just a quick re-serve.",
        safety="Adult prepares the food; nothing hot or glass.",
    ),
    "new_one_person_band": c(
        say="Let's make a whole scene with our voices and bodies—wind, footsteps, a door. Ready? Action!",
        steps="Build a short sound-only scene using voice and body (wind, footsteps, a knock), like a one-person sound-effects band.",
        turns="Each player builds their own mini scene.",
        end="After everyone has performed a soundscape.",
        easier="Three sounds to tell a tiny story.",
        harder="A two-player 'duet' soundscape.",
        coop="The family guesses each other's scenes.",
        recovery="A missing sound just gets 'looped' by the narrator.",
    ),
    "new_grandparent_then_now": c(
        say="Grandparent, how was school different when you were our age? Tell us one thing!",
        steps="Ask a grandparent (nearby or on video) how one everyday thing—school, phones, sweets—was different when they were young, then compare to today.",
        turns="Each child asks one 'then and now' question.",
        end="After a few questions or stories.",
        easier="Ask one yes/no question first.",
        harder="Compare the old way to today's in one sentence.",
        coop="Listening to family history is a shared treasure.",
        recovery="A forgotten detail is fine—share it as a question instead.",
    ),
    "new_ice_melt_race": c(
        say="Which ice cube will melt first—the one on the plate, in water, or near the window? Let's predict and find out!",
        setup="Two or three ice cubes and different surfaces/containers.",
        steps="Place ice cubes on different surfaces, predict which melts first, then check and discuss why.",
        turns="Each player predicts one cube.",
        end="When a winner is declared and the 'why' is discussed.",
        easier="Compare just two cubes: in water vs on a plate.",
        harder="Predict the exact order and time them.",
        coop="Hypothesize together, then observe together.",
        recovery="A tied race is a chance to try one more surface.",
        safety="Wipe up water as it melts.",
    ),
}
