"""How-to-play cards for the 20 existing Help activities."""
def c(**kw):
    return {k: v for k, v in kw.items() if v}

CARDS = {
    "help_laundry_match": c(
        say="I'll hold up one sock — find its partner! Let's see the whole pile matched as a team.",
        setup="A pile of clean laundry, especially socks and pairs.",
        steps="Match and fold together: one person finds pairs, another folds, another sorts into piles.",
        turns="Rotate jobs so everyone tries matching, folding, and sorting.",
        end="When the pile is folded and sorted.",
        easier="Adult separates socks; child matches partners.",
        harder="Fold by a color order the child decides.",
        coop="It's a shared job, finished by everyone's effort.",
        recovery="A matched 'wrong' pair just gets unmade and rematched.",
    ),
    "help_fold_teach": c(
        say="I'll show you one fold — now you show me how to do it back.",
        setup="A clean towel or a shirt.",
        steps="Learn one fold from the adult, practice it, then teach it back step by step.",
        turns="Adult teaches, child mirrors, then child teaches the adult.",
        end="When the child has taught the fold back to the adult.",
        easier="Fold a hand towel.",
        harder="Fold a fitted sheet together (a fun challenge).",
        coop="Teaching back is the success, not folding perfectly.",
        recovery="If the fold gets messy, unfold and go one step at a time.",
    ),
    "help_order_table": c(
        say="With my help, you'll order for all of us at the restaurant. Ready to be our voice?",
        steps="With adult support, the child greets and orders for the family—names a dish, checks drinks, says thank you.",
        turns="The child leads; the adult quietly supports and fills gaps.",
        end="After the order is placed.",
        easier="Order just one item or your own drink.",
        harder="Ask the server one polite question.",
        coop="The adult is there so it feels safe, not so the child is quizzed.",
        recovery="A stutter or pause is normal—the adult gently helps finish.",
        safety="The adult handles money and any tricky choices.",
    ),
    "help_jacket_flip": c(
        say="Lay your jacket on the floor, arms in the sleeves, and flip it over your head. Ready?",
        setup="The child's own jacket.",
        steps="Lay the jacket open on the floor, put both arms into the sleeves, then flip it up and over to put it on.",
        turns="Each child practices their own coat flip.",
        end="When each one can do the flip, even slowly.",
        easier="Adult holds the jacket steady.",
        harder="Do it standing without a floor start.",
        recovery="A stuck sleeve just gets wiggled out and tried again.",
        safety="Do it in open space, away from walls and furniture.",
    ),
    "help_gift_wrap_partner": c(
        say="Let's wrap this gift together—you can tape and decorate, I'll handle the tricky folds.",
        setup="Wrapping paper, tape, scissors, and a gift.",
        steps="One person measures and cuts, one folds and tapes, then both decorate with the child adding the bow and tag.",
        turns="Swap who does the cutting each gift.",
        end="When the gift is wrapped and tagged.",
        easier="Adult folds; child sticks tape and adds stickers.",
        harder="The child plans the paper placement and measures with a ruler.",
        coop="One gift, two pairs of hands—a team effort.",
        recovery="If the paper rips, patch it with a fun 'extra' layer.",
        safety="Adult handles scissors.",
    ),
    "help_flower_finder": c(
        say="Let's gather safe, fallen flowers and make a bouquet for someone.",
        setup="A small jar or paper, and fallen (already off the plant) flowers or leaves.",
        steps="Collect only safe fallen blooms, arrange them in a jar or wrap them, and add a note.",
        turns="Each person gathers and arranges one part.",
        end="When the bouquet is ready to give.",
        easier="Adult picks; child arranges.",
        harder="Arrange in a color pattern.",
        recovery="Wilted or dropped stems just get re-arranged.",
        safety="Only fallen plants; wash hands after; no unknown berries.",
    ),
    "help_set_table_pattern": c(
        say="Let's set the table in a pattern—plate, then cup, then fork—round and round.",
        setup="Plates, cups, and utensils.",
        steps="Set each place following a repeating pattern the child chooses, counting as you go.",
        turns="The child decides the pattern; everyone helps carry.",
        end="When every seat is set.",
        easier="Place just plates first.",
        harder="Include napkin folds or a centerpiece.",
        coop="It's a real family job done together.",
        recovery="A mixed-up setting is easy to fix and re-count.",
    ),
    "help_snack_assembly": c(
        say="We're a snack assembly line. You add the crackers, I'll add the cheese—go!",
        setup="Snack components (crackers, fruit, cheese) on a tray.",
        steps="Set up an assembly line where each child adds one ingredient to each snack, passing it down the line.",
        turns="Rotate stations so everyone tries each job.",
        end="When enough snacks are made for everyone.",
        easier="Two stations only.",
        harder="Count snacks and check everyone gets one.",
        coop="The line only works if each person does their part.",
        recovery="A dropped snack just gets remade quickly.",
        safety="Adult checks for allergies and handles cutting.",
    ),
    "help_grocery_color_hunt": c(
        say="As we put groceries away, let's find the red things, then the green—what color next?",
        setup="The shopping, sorted near the kitchen.",
        steps="Put groceries away while hunting by color: find all the red packages, then green, and so on.",
        turns="Each child picks the next color and leads that sort.",
        end="When everything is put away.",
        easier="Sort into just 'cold' and 'pantry.'",
        harder="Sort by color within the fridge too.",
        coop="Everyone pitches in on one shared put-away.",
        recovery="A heavy or high item is handed to the adult.",
        safety="Adult handles glass jars and anything heavy or sharp.",
    ),
    "help_toy_repair": c(
        say="Let's be toy repair inspectors. What's wrong with this toy, and how can we help fix it?",
        setup="A toy with a fixable issue (loose string, sticker peeling, stuck wheel).",
        steps="Inspect the toy, name the problem, and plan a safe fix together, then carry it out with adult help where needed.",
        turns="Each child inspects and reports one finding.",
        end="When the toy is fixed or a plan is made.",
        easier="A sticker that needs re-sticking.",
        harder="Rebuild or restring a simple toy.",
        coop="Diagnosing and fixing is teamwork.",
        recovery="If a fix needs tools, the adult does that part.",
        safety="Adult handles tools and small parts.",
    ),
    "help_sock_sorting": c(
        say="Let's race—gently—to match and sort all the socks. Three, two, one-go!",
        setup="A clean pile of mixed socks.",
        steps="Match socks into pairs and sort them by owner or color, working together at a fun, gentle pace.",
        turns="Each child takes a turn being the 'sorter lead.'",
        end="When every sock is paired and sorted.",
        easier="Just match pairs, no sorting.",
        harder="Sort by color, then by size.",
        coop="It's a shared, silly race—everyone wins together.",
        recovery="An unmatched sock starts a fun 'lost sock' mystery pile.",
    ),
    "help_water_right_amount": c(
        say="How much water does this plant need? Let's look at it and decide together, then water it.",
        setup="A houseplant and a small watering can or cup.",
        steps="Check the plant's soil, decide the right amount, water it gently together, and notice the result.",
        turns="Each child helps choose a plant and water it.",
        end="When the plants are watered and checked.",
        easier="Adult measures; child pours.",
        harder="Keep a tiny 'plant care' note about each plant.",
        coop="Caring for a living thing is a shared job.",
        recovery="A little too much water just means wiping the saucer.",
        safety="Adult handles heavy watering cans; wipe spills.",
    ),
    "help_pack_outing_bag": c(
        say="Let's plan what we need for our outing and pack the bag together.",
        setup="A bag and the items you'll need for a planned outing.",
        steps="Make a short list together, gather each item, and pack the bag in a sensible order.",
        turns="Each child is in charge of one category (water, snack, jacket).",
        end="When the bag is packed and checked off.",
        easier="Pack just the snack.",
        harder="Check off a written list as you pack.",
        coop="Planning and packing is a team job.",
        recovery="A forgotten item just gets added and packed.",
    ),
    "help_wipe_notice": c(
        say="Let's wipe this table and notice what changes as it gets clean.",
        setup="A damp cloth and a table or counter.",
        steps="Wipe a surface together and pause to notice what changed—dust gone, shine back—before moving on.",
        turns="Each child wipes one section and reports a 'noticing.'",
        end="When the surface is clean and everyone noticed something.",
        easier="Wipe one small area.",
        harder="Wipe and then put the cloth away properly.",
        coop="Cleaning together makes the noticing more fun.",
        recovery="A missed spot is just another section to wipe.",
        safety="Damp cloth; no harsh cleaners for children.",
    ),
    "help_pick_clothes": c(
        say="Let's pick tomorrow's outfit—check the weather, then choose clothes you'll love.",
        setup="The child's own clothes and a weather check.",
        steps="Look at tomorrow's weather, then choose a full outfit (top, bottom, socks, outer layer) and lay it out.",
        turns="The child chooses; the adult asks one useful question (warm or cool?).",
        end="When the outfit is laid out for tomorrow.",
        easier="Pick just the top.",
        harder="Choose a second 'backup' in case of rain.",
        coop="The child leads; the adult supports the decision.",
        recovery="A weather surprise just means swapping one layer.",
    ),
    "help_thank_you_delivery": c(
        say="Who helped us this week? Let's make a small thank-you and deliver it.",
        setup="Paper and something to write or draw with (or a spoken thank-you).",
        steps="Choose who to thank, draw or write a short thank-you, then deliver it (in person or by mail).",
        turns="Each child gets to thank someone.",
        end="When every thank-you is delivered or sent.",
        easier="A spoken or drawn thank-you.",
        harder="Write your own words and sign it.",
        coop="Gratitude is a family practice, not a task.",
        recovery="If someone is hard to reach, a mailed card still counts.",
    ),
    "help_family_lost_found": c(
        say="Let's run our family lost-and-found. Where does this lost item belong?",
        setup="A box or tray and any 'lost' items around the house.",
        steps="Gather misplaced items into a tray, then work as a team to return each to its real home.",
        turns="Each child picks an item and finds its home.",
        end="When the tray is empty and things are back.",
        easier="Return just one kind of item (socks).",
        harder="Make labels so items know where they belong.",
        coop="It's a family tidy mission, not one person's chore.",
        recovery="Unsure where it goes? Decide together or find a new home.",
    ),
    "help_measure_recipe": c(
        say="Let's measure and count our ingredients for this recipe—you can do the scooping.",
        setup="A simple recipe and measuring cups/spoons.",
        steps="Read the amounts together, then measure and count each ingredient, adding them in order.",
        turns="Each child measures one ingredient.",
        end="When the recipe is mixed and ready (or baked with adult help).",
        easier="Count out crackers or fruit pieces.",
        harder="Read the numbers and fractions aloud.",
        coop="Everyone's measured part builds the whole recipe.",
        recovery="A mismeasure just gets corrected before it affects the dish.",
        safety="Adult handles the oven, heat, and any chopping.",
    ),
    "help_quiet_cleanup": c(
        say="Let's finish cleanup as a quiet mission—soft voices, calm moves, together.",
        setup="The toys or items to put away.",
        steps="Pick up one thing at a time and put it away gently, keeping it calm and quiet.",
        turns="Each child takes a zone or a type of item.",
        end="When the space is clear.",
        easier="Put away just your own toys.",
        harder="Sort by home as you put each away.",
        coop="Low-energy and low-voice, everyone helps.",
        recovery="A slow start is fine; just begin with one item.",
    ),
    "help_teach_household_skill": c(
        say="What's a skill you know that you could teach me? Let's see you teach it.",
        setup="Anything the child can do—making a bed, setting a spot, folding a napkin.",
        steps="The child picks a household skill they can do and teaches the adult step by step, then watches the adult try.",
        turns="The child is the teacher; the adult is the learner.",
        end="When the child has taught the skill and the adult tries it.",
        easier="The child narrates as the adult does it.",
        harder="The child can't use words—demonstrate only.",
        coop="Flipping the roles builds confidence and respect.",
        recovery="If the child forgets a step, they can do it themselves and explain.",
    ),
}
