"""How-to-play cards for the 14 existing Talk ideas that had no docs card."""
def c(**kw):
    return {k: v for k, v in kw.items() if v}

CARDS = {
    "talk_alphabet_conversation": c(
        say="'Let's talk in alphabet order. My sentence starts with A — 'A brand-new day smells like toast.' Your turn starts with B.'",
        steps="Go around, each speaking one sentence that starts with the next letter. Help each other and skip hard letters without ending the game.",
        turns="One sentence per person per round; anyone may offer a starting word.",
        end="Finish at Z, or stop after two full rounds.",
        easier="Say just one word per letter instead of a full sentence.",
        harder="Every sentence must connect to the one before it.",
        recovery="If someone gets stuck, the group offers three starting words and the speaker picks one.",
    ),
    "talk_sentence_charades": c(
        say="'I'll act out a whole sentence — one word at a time. Guess the word, then the sentence.'",
        steps="Pick a short sentence and act each word clearly (noun, then verb, then object), with gestures and sound effects.",
        turns="One actor, one guess per word; the correct guesser acts next.",
        end="Everyone who wants to acts once, or three sentences.",
        easier="Act a single word instead of a sentence.",
        harder="No sound effects, gestures only.",
        recovery="The actor can repeat or exaggerate a word after a full round of guesses.",
    ),
    "talk_seven_real_questions": c(
        say="'Ask me something you genuinely want to know — and I'll really listen. Then I might ask you one back.'",
        steps="One person asks a real, open question ('What was the best part of your day?') and the group just listens without fixing or advising.",
        turns="Each player gets one 'real question' turn; the person asked may pass.",
        end="Finish after everyone who wants to has asked and answered once.",
        easier="Use the question jar or a starter list.",
        harder="Ask a follow-up question before moving on.",
        recovery="If an answer gets laughed at, the asker thanks them and the group moves on kindly.",
    ),
    "talk_good_deed_draft": c(
        say="'Let's draft one small kind act for someone. It can be tiny — a note, a smile, a yes.'",
        steps="Name the person and one small kind thing, then plan the simplest way to do it (after the game).",
        turns="Each person drafts one deed; the group helps, never grades.",
        end="Everyone who wants shares one deed, then pick one to actually do.",
        easier="Adult offers two example deeds to choose from.",
        harder="Plan the deed's 'when and how' in one sentence.",
        recovery="An idea that won't work goes on a 'someday' list instead of being rejected.",
    ),
    "talk_adjective_faces": c(
        say="Make the silliest face you can for the word 'proud.' Now 'grumpy.' Now 'surprised.'",
        steps="One player calls a feeling word; everyone makes an exaggerated face and pose to match. No words needed.",
        turns="Each player gets to call one word, then everyone performs.",
        end="Three to five words, then stop while it's still fun.",
        easier="Start with happy, sad, sleepy.",
        harder="Add an action to the face, like a stomp or a flutter.",
        recovery="Whatever face you make is the right one — there's no wrong answer.",
    ),
    "talk_describe_and_draw": c(
        say="'Describe a simple picture to me without naming it, and I'll try to draw exactly what you say.'",
        steps="One player secretly looks at an object or picture and describes it line by line; the other draws from the words alone.",
        turns="Swap after each drawing; the describer may never point at the thing.",
        end="Two drawings each, then admire both versions.",
        easier="Describe a simple shape or a single object.",
        harder="Add exactly two clues per line and nothing more.",
        recovery="If the drawing drifts, the drawer asks one yes/no question and continues.",
    ),
    "talk_finish_my_story": c(
        say="'I'll start a story and stop at a turning point. You finish it — then tell me a different ending.'",
        steps="Adult starts a familiar-feeling story and stops before the ending; the child invents one ending, then a completely different one.",
        turns="Alternate who starts and who finishes each round.",
        end="Two endings per story, then swap.",
        easier="Offer two 'what if' choices for the ending.",
        harder="The new ending must change something earlier in the story.",
        recovery="Any ending is a good ending — laugh and move to a fresh story.",
    ),
    "talk_restaurant_reporter": c(
        say="'We're reporters for the Dinner News. Quietly describe what you see — the colors, the sounds, the people.'",
        steps="Speak like a news reporter, low and descriptive, about the restaurant or room scene around you, without pointing rudely.",
        turns="Each player gives one short 'broadcast'; the adult cues the next reporter.",
        end="After the food arrives or everyone has broadcast once.",
        easier="Describe just colors and sounds.",
        harder="Turn the report into a story with a beginning and 'headline.'",
        recovery="You never have to report on strangers or private moments.",
        safety="Keep voices low and never comment on people's bodies or belongings.",
    ),
    "talk_toy_press_conference": c(
        say="Our toy is holding a press conference today. Toys, what's the question you'd like to ask first?",
        steps="A favorite stuffed toy 'holds a press conference'; the family raises hands and asks it questions, and the toy (played by whoever holds it) answers.",
        turns="Everyone gets one question; the toy holder answers in character.",
        end="Three questions each, or until the toy 'has to go.'",
        easier="The adult plays the toy and answers silly questions.",
        harder="The toy must work every family member's name into its answers.",
        recovery="If the toy runs out of answers, it can ask a question back.",
    ),
    "talk_what_grownups_know": c(
        say="'If you could tell grown-ups one thing they'd understand better, what would it be?'",
        steps="Anyone may offer one thing they wish grown-ups understood; the grown-ups listen without arguing or fixing.",
        turns="Each willing person shares one; passing is always fine.",
        end="Close with a thank-you, not a lecture or a solution.",
        easier="Answer a lighter prompt, like 'what's the best part of your day?'",
        recovery="The goal is being heard, so no answer is debated.",
        privacy="Answers stay in the family; nothing is recorded or judged.",
    ),
    "talk_memory_by_color": c(
        say="If today had a color, what would it be? Now tell me the memory that goes with it.",
        steps="One player names a color and shares a memory that color brings (that day's mood, a place, a feeling); others may add one memory each.",
        turns="One color + memory per player, in a circle.",
        end="One round, then ask which memory the family wants to keep.",
        easier="Share a favorite color and one happy thing about today.",
        harder="The next player's color must connect to the previous memory.",
        recovery="Passing is allowed — colors and memories are both optional.",
    ),
    "talk_compliment_detective": c(
        say="'I'm a compliment detective. I noticed something true about you — can you guess what, in one try?'",
        steps="One player gives a specific, truthful, kind 'clue' about someone, and others guess or simply receive it warmly.",
        turns="Each player gets to give and receive once.",
        end="Everyone who wants to has given a compliment.",
        easier="Name the person and say the nice thing directly.",
        harder="The compliment must mention a specific moment, not a general trait.",
        recovery="Compliments are always welcomed, never returned competitively.",
    ),
    "talk_one_minute_family_news": c(
        say="'And now, the family news — in sixty seconds. What's our top headline today?'",
        steps="Take turns delivering a one-minute 'newscast' of made-up or true family headlines (weather in the kitchen, sports in the park).",
        turns="Each player hosts one short segment; clap politely at handoffs.",
        end="After each willing player has a turn.",
        easier="Adult reads the first 'headlines' and the child repeats them.",
        harder="Every headline must rhyme.",
        recovery="Rename flubbed lines as comedy and keep going.",
    ),
    "talk_question_jar": c(
        say="Reach into our invisible question jar. What question came out — and how will you answer it?",
        steps="Pick (or imagine) a family question, answer it yourself, then invite the next person to answer the same one.",
        turns="One question, answered by everyone in turn.",
        end="One to three questions, or when the food arrives.",
        easier="Use concrete prompts like favorite food or color.",
        harder="Questions must be about wishes, memories, or hopes.",
        recovery="Passing is always allowed; nobody must reveal more than they want.",
    ),
}
