"""How-to-play cards for the 20 existing Perform activities."""
def c(**kw):
    return {k: v for k, v in kw.items() if v}

CARDS = {
    "perf_penetrating_palm": c(
        say="Watch closely—I'm going to make my thumb look like it goes right through my hand!",
        steps="Learn the no-prep 'penetrating palm' illusion, practice the reveal slowly, then explain sneaky part (misdirection) to your audience.",
        turns="Each performer shows the trick, then an audience member guesses how it works.",
        end="When everyone who wants to has performed once.",
        easier="Adult demonstrates first.",
        harder="Add a funny presentation line before the reveal.",
        coop="No mocking bad tricks—applause for every attempt.",
        recovery="If the trick is spotted, the secrets now belong to the family.",
    ),
    "perf_growing_thumb": c(
        say="Look at my thumb... is it getting longer? It's growing!",
        steps="Master the growing-thumb optical illusion, present it to the family, then reveal (or let them guess) how the fake thumb works.",
        turns="Each performer gets a turn; rotate audience.",
        end="After everyone has performed.",
        easier="Watch an adult do it first.",
        harder="Do the trick two ways and let the family spot the difference.",
        coop="Applaud every version—silly included.",
        recovery="A fumbled thumb is a funny moment, not a failure.",
    ),
    "perf_missing_finger": c(
        say="Watch—one, two, three... and my finger disappears! No wait, there it is.",
        steps="Learn the classic missing-finger sleight, practice the reveal, and present it with a showman's pause.",
        turns="Each performer shows it; others try to find the 'missing' finger.",
        end="After everyone has had a turn.",
        easier="Adult performs; child guest-stars.",
        harder="Add a sound effect or a wink at the reveal.",
        coop="The family roots for the magician.",
        recovery="A visible finger just makes everyone laugh.",
    ),
    "perf_rubber_band_escape": c(
        say="I'm trapped! But with one quiet move... the rubber band escapes my fingers.",
        setup="A rubber band (loose, not tight).",
        steps="Learn a rubber-band escape, rehearse the move, then present it in a mini magic show.",
        turns="Each performer gets a turn; audience guesses the move.",
        end="After everyone has shown an escape.",
        easier="Adult demonstrates the move first.",
        harder="String three tricks into one short show.",
        coop="Cheer every escape, even the obvious ones.",
        recovery="If the band won't cooperate, loosen it and try again.",
        safety="Use only loose bands; never snap them.",
    ),
    "perf_adjective_face_off": c(
        say="Say the same line as me—but with a completely different feeling. Ready? Action!",
        steps="Two players say the same short line, each with a wildly different emotion (one proud, one sleepy), and the family reacts.",
        turns="Every pair gets one face-off.",
        end="When all willing players have done a face-off.",
        easier="One player does two emotions back to back.",
        harder="A third player joins mid-line with a surprise emotion.",
        coop="It's comedy, not a contest—both performances 'win.'",
        recovery="A confused face is just another performance choice.",
    ),
    "perf_one_minute_talent": c(
        say="Let's see your talent—you've got one minute. Ready? Showtime!",
        steps="Each person presents a one-minute talent (a trick, a dance, a funny story) while the family watches and applauds.",
        turns="One performer at a time; the family is the audience.",
        end="When everyone willing has shared.",
        easier="Thirty seconds is fine.",
        harder="Link your talent to the last person's.",
        coop="Applause for every attempt is the rule.",
        recovery="If someone forgets, they can 'freestyle' instead.",
    ),
    "perf_teach_back_toy": c(
        say="Teach your toy how to do this. It's listening very carefully!",
        steps="Explain or demonstrate a skill to a favorite toy 'student,' speaking slowly so the toy can learn.",
        turns="Each child teaches a different toy.",
        end="When each toy has 'learned' a skill.",
        easier="Demonstrate without words.",
        harder="Answer the toy's 'questions' out loud.",
        coop="Teaching is the point—the toy always learns.",
        recovery="If the child freezes, the toy asks a silly question to help.",
    ),
    "perf_no_words_restaurant": c(
        say="Let's order at this table without any words—only gestures. Ready?",
        steps="At a quiet table, communicate the order using only gestures and expressions until the 'waiter' guesses.",
        turns="Each player 'orders' one thing with gestures.",
        end="After everyone has ordered one gesture item.",
        easier="Adult is the first waiter to model it.",
        harder="Order a silly, impossible dish.",
        coop="Guessing wrong just adds to the comedy.",
        recovery="If communication breaks down, one word is allowed.",
        safety="Keep it quiet and respectful of nearby tables.",
    ),
    "perf_sync_finger_wave": c(
        say="Let's make our fingers do the wave at the same time—ready, and... go!",
        steps="Coordinate a 'wave' that travels across joined hands or fingers, timing your moves to pass it along smoothly.",
        turns="Start slow, then trade who starts the wave.",
        end="When you can pass the wave twice in a row in sync.",
        easier="Pass the wave slowly.",
        harder="Change direction mid-wave.",
        coop="Being in sync together IS the goal.",
        recovery="A dropped wave just restarts and everyone laughs.",
    ),
    "perf_mini_magic_show": c(
        say="Welcome to our one-minute magic show! First trick—ta-da!",
        steps="Rehearse two no-prep tricks, plan a short presentation order, then perform a mini magic show for the family.",
        turns="Each performer runs their mini show; the family is the audience.",
        end="After every show and a round of applause.",
        easier="One trick plus a bow.",
        harder="Connect the two tricks with a story line.",
        coop="The audience is supportive, not testing.",
        recovery="A flubbed trick becomes a comedy beat.",
    ),
    "perf_sound_effect_story": c(
        say="I'll tell a story—you supply the sound effects! Every time you hear 'ding,' do the bell.",
        steps="One person narrates a story while the others add live sound effects with voice, hands, and body at the right moments.",
        turns="Anyone can jump in with a fitting sound; rotate narrator.",
        end="When the story reaches its ending.",
        easier="Everyone makes one repeated sound.",
        harder="Each character gets its own assigned sound.",
        coop="The sound-effects team makes the story come alive together.",
        recovery="A wrong sound just becomes part of the story.",
    ),
    "perf_dance_other_decade": c(
        say="Let's learn a dance step from another decade—what was dancing like back then?",
        steps="A grown-up or grandparent shows a simple dance step from their era, and everyone practices and performs it together.",
        turns="The older generation teaches; the younger generation mirrors.",
        end="When the family can do the step together.",
        easier="A simple two-step.",
        harder="Add a spin or a handshake move.",
        coop="Learning a shared step connects the generations.",
        recovery="Wrong footing just means you invented a new step.",
        safety="Go at the comfort of the oldest dancer.",
    ),
    "perf_reverse_roles": c(
        say="For one minute, you're in charge and I'll follow! What should I do?",
        steps="Swap roles for a short round: the child gives the directions and the adult follows them exactly.",
        turns="Each person gets a turn 'leading' for a minute.",
        end="After everyone has led once.",
        easier="The child gives three simple commands.",
        harder="The adult must follow exactly, no negotiating.",
        coop="Following well is the adult's job this time.",
        recovery="A funny command is part of the fun.",
        safety="Keep commands space-safe (no running near edges).",
    ),
    "perf_three_prop_charades": c(
        say="Act out a scene using only these three props—and no real talking. Ready?",
        setup="Three safe household objects or gestures.",
        steps="Choose a scene and act it out using only the three chosen props or gestures, letting the family guess.",
        turns="Each player picks three props and performs.",
        end="After everyone has had a turn.",
        easier="Use just one prop.",
        harder="The props can't be used their ordinary way.",
        coop="Guessing together is part of the performance.",
        recovery="A stuck actor can add one silent gesture.",
    ),
    "perf_family_news_broadcast": c(
        say="And now, the family news live from the living room!",
        steps="Stage a short newscast with family headlines—the weather in the kitchen, sports in the garden—each player hosting a segment.",
        turns="Each player anchors one segment; the family is the studio audience.",
        end="When the broadcast signs off.",
        easier="Each player shares one headline.",
        harder="Add a commercial break.",
        coop="It's a team broadcast—every anchor matters.",
        recovery="A line flub becomes a blooper reel moment.",
    ),
    "perf_slowest_race_announcer": c(
        say="Steady now... the slowest one wins! Anyone can cross the line, but the slowest is champion.",
        steps="A gently competitive race where the goal is to be slowest, while an announcer comments dramatically on each slow step.",
        turns="Each player takes a turn as announcer.",
        end="When everyone has crossed or a few minutes pass.",
        easier="Just try to be slow, no announcing.",
        harder="Freeze for a count each time the announcer says 'hold.'",
        coop="Everyone 'wins' at being delightfully slow.",
        recovery="A fast step just means a dramatic 'oh no, they sped up!'",
        safety="Clear, flat space.",
    ),
    "perf_mystery_voice": c(
        say="Speak in a silly or disguised voice—can we guess who's talking?",
        steps="One player speaks or reads a line in a disguised, squeaky, or deep voice while others guess who it is.",
        turns="Each player gets a go at disguising their voice.",
        end="After everyone has been guessed or given up.",
        easier="Say one word in a weird voice.",
        harder="Disguise a whole sentence without breaking.",
        coop="Guessing is collaborative fun.",
        recovery="If nobody guesses, the speaker reveals with a funny bow.",
    ),
    "perf_copy_my_hands": c(
        say="Do what I do with my hands—slowly now. Ready?",
        steps="One player leads a slow hand routine (tap, wave, twist); everyone mirrors; then the leader swaps.",
        turns="Each player leads a short routine.",
        end="After everyone has led once.",
        easier="Copy single gestures.",
        harder="Chain three moves and lead them faster.",
        coop="Staying together is the goal.",
        recovery="If you lose the thread, the leader repeats the last move.",
    ),
    "perf_trick_explanation": c(
        say="Now for the real magic: explain your trick so clearly that a younger kid could do it.",
        steps="After performing a simple trick, explain the misdirection and steps clearly enough that a younger child could follow.",
        turns="Each performer also becomes the explainer.",
        end="When each trick has been explained (or 'passed on').",
        easier="Use a hand-drawn picture to explain.",
        harder="No pointing—only words.",
        coop="Passing the secret on is the real win.",
        recovery="If the explanation muddles, break it into two smaller steps.",
    ),
    "perf_grandparent_signature": c(
        say="Grandparent, what's a skill you're famous for? Show us—we want to learn it and perform it with you.",
        steps="Invite a grandparent (nearby or on video) to teach a signature skill, then practice and perform it together as a family.",
        turns="The grandparent demonstrates; the family mirrors and performs.",
        end="When the family can present the skill together.",
        easier="Copy a simple gesture or saying.",
        harder="Chain it into a mini routine.",
        coop="This is intergenerational teamwork.",
        recovery="Everyone goes at the grandparent's comfortable pace.",
    ),
}
