"""How-to-play cards for the 20 existing Think activities."""
def c(**kw):
    return {k: v for k, v in kw.items() if v}

CARDS = {
    "act_reverse_forks": c(
        say="Here's a tiny arrangement puzzle. It's almost right — figure out the one move that makes it correct.",
        setup="A few forks (or spoons or safe objects) arranged on the table.",
        steps="Set up the fork arrangement, let everyone look, then look for the single move that reverses or fixes the pattern.",
        turns="Each player proposes one move; test it together.",
        end="When the arrangement is correctly reversed.",
        easier="Adult points out the two pieces involved.",
        harder="Two moves allowed, or abstract the clue.",
        coop="You solve it as a team; wrong moves are just hypotheses.",
        recovery="If stuck, give a clue about which side is off.",
        safety="Use clean, blunt utensils.",
    ),
    "act_sound_sequence": c(
        say="Listen: tap-tap-clap. Can you copy it, then add one sound of your own?",
        steps="One player makes a short sound sequence; the next copies it and adds a new sound, growing the pattern.",
        turns="Each round the sequence grows by one sound.",
        end="When the sequence reaches a set length or two rounds each.",
        easier="Two sounds, with visual taps shown.",
        harder="Keep a steady rhythm as well as the order.",
        coop="Help each other rebuild; nobody gets out.",
        recovery="If lost, slow down and copy just the last two sounds.",
        safety="Use voice/hands; gentle taps for hard-of-hearing players.",
    ),
    "act_mirror_dot_drawing": c(
        say="Look at this half-drawing with the dots. Draw the exact mirror on the other side of the line.",
        setup="Grid or lined paper with half a dot-pattern drawn.",
        steps="Copy the dotted pattern as a mirror image across the center line, counting squares to match.",
        turns="Each player draws one mirrored picture, then compares.",
        end="When both drawings are done and compared.",
        easier="A simple 3-dot pattern.",
        harder="A large pattern or adding colors mirrored too.",
        coop="Explain your trick to a partner as you go.",
        recovery="Count the squares again; erase and fix one dot at a time.",
    ),
    "act_modified_tic_tac_toe": c(
        say="Let's change one rule of tic-tac-toe and discover the new best way to play.",
        setup="Paper and pencil, or a drawn grid.",
        steps="Pick a rule to change (bigger board, first to three, or a piece that 'moves'), then play and notice how thinking changes.",
        turns="Players alternate turns; after a game, propose the next rule change.",
        end="After two or three rule-changed games.",
        easier="Adult chooses a simple rule change.",
        harder="Players invent the rule together without ending the game in a draw.",
        recovery="A confusing rule gets re-explained and tried again.",
    ),
    "act_which_rule_changed": c(
        say="Watch how I sort these. Shut your eyes — I changed one rule. Which one?",
        setup="A small group of household objects that can be sorted by color, size, shape, or type.",
        steps="Sort a few objects by one clear rule; then secretly change it and re-sort; everyone spots what changed.",
        turns="Each player gets to be the rule-changer.",
        end="After everyone has had a turn.",
        easier="Two categories only.",
        harder="Change two rules at once.",
        coop="Guessing is collaborative — work it out together.",
    ),
    "act_sorting_machine": c(
        say="You're the sorting machine! Sort these into two trays — find your rule and keep it consistent.",
        setup="Two trays or bowls and a pile of mixed safe objects.",
        steps="The child chooses a sorting rule and sorts the objects accordingly; the machine must be consistent in its choices.",
        turns="The 'machine' sorts; family asks questions to guess the rule.",
        end="When the pile is sorted and someone names the rule.",
        easier="Sort by a visible property like color.",
        harder="Sort by a hidden rule (things with a handle) and let others guess.",
        recovery="The machine can 'reset' and restate its rule if it wobbles.",
    ),
    "act_human_algorithm": c(
        say="I'll read you a little program of steps. Follow the steps exactly — like you're the machine.",
        steps="The adult reads a short ordered 'program' (e.g. take one cup, put it left, take another, put it right) and the child follows it precisely.",
        turns="Then the child writes a program for the adult to follow.",
        end="When both programs run correctly.",
        easier="Two-step programs.",
        harder="Add a 'repeat until' or an 'if' condition.",
        coop="Debugging together is the point.",
        recovery="If a step is missed, 'rewind' one step and continue.",
    ),
    "act_debug_instructions": c(
        say="I'm going to give you intentionally broken instructions. Find the bug and fix it!",
        steps="The adult gives faulty step-by-step instructions for a tiny task; the child follows to find where it fails, names the bug, and fixes the instruction.",
        turns="Then the child writes some broken instructions for the adult.",
        end="After each has 'debugged' one set.",
        easier="A one-step error in a short list.",
        harder="Two subtle bugs or a missing step that causes a chain effect.",
        coop="Bug-hunting is team detective work.",
        recovery="If you can't find it, ask for one hint about which step is off.",
    ),
    "act_pattern_under_cups": c(
        say="Watch where I put the shapes under the cups. Now — which cup hides the triangle?",
        setup="Three cups and two or three small objects.",
        steps="Hide objects under cups in a visible pattern, let everyone watch, then mix (or don't) and predict where each is.",
        turns="Each player gets to be the hider once.",
        end="After everyone has had a turn.",
        easier="Keep objects visible while placing them.",
        harder="Add a swap move and track it.",
        coop="Work out predictions together, then reveal.",
    ),
    "act_mystery_sound": c(
        say="You can't see it — but you can hear it. What do you think this object is?",
        setup="A safe household object hidden behind a screen or turned away.",
        steps="Make a sound with the hidden object (shake, tap, pour) and let everyone guess what it is before revealing.",
        turns="Each player hides and sounds one object.",
        end="After everyone has had a turn.",
        easier="Objects with obvious sounds (bell, shaker).",
        harder="Silent-ish objects with subtle sounds.",
        recovery="Give one texture or weight clue if nobody guesses.",
        safety="Only safe household objects; nothing sharp or loud.",
    ),
    "act_color_photo_hunt": c(
        say="Let's hunt for a list of colors — and photograph each one we find around the house.",
        setup="A phone/camera and a list of colors.",
        steps="Take turns finding an object matching each color on the list and photographing it.",
        turns="Each player is the photographer for a color.",
        end="When every color has a photo.",
        easier="Three colors in one room.",
        harder="Each photo must contain two listed colors, or a color by name only.",
        recovery="A missing color can be 'made' with a drawing or paint swatch.",
        safety="No climbing or unsafe reaches for a photo.",
    ),
    "act_predict_paper_flight": c(
        say="Let's predict where this paper plane will land, then test our guess and measure the miss.",
        setup="Paper planes and a clear throwing lane.",
        steps="Fold a plane, predict (how far, which wall), throw gently, and measure where it actually lands.",
        turns="Each person predicts then throws their own.",
        end="After everyone has tested one or two designs.",
        easier="Predict just 'closer' vs 'farther' than a marker.",
        harder="Predict in exact steps, then count the difference.",
        recovery="If it dives, adjust and re-predict — that's the experiment.",
        safety="Throw gently in open space.",
    ),
    "act_floating_pepper": c(
        say="Sprinkle pepper on the water. Now — what do you think happens if I touch the surface with soap?",
        setup="A bowl of water, pepper, and a drop of dish soap.",
        steps="Sprinkle pepper on the surface, predict what soap will do, then touch a soapy finger to the center and watch the pepper dart away.",
        turns="Clean/re-season between rounds and let each prediction be tested.",
        end="After two or three clean trials.",
        easier="Adult handles the soap.",
        harder="Try it again with a second bowl and predict the difference.",
        coop="Make predictions together, then test.",
        recovery="If it doesn't work, use fresh water and a new soap drop.",
        safety="Adult handles soap; no one tastes the water.",
    ),
    "act_sink_or_float": c(
        say="Before we drop each thing, guess: sink or float? Then test and sort into two piles.",
        setup="A bowl of water and a selection of safe kitchen/laundry objects.",
        steps="For each object, predict sink or float, drop it gently, and sort it by the real result.",
        turns="Each player picks the next object to test.",
        end="When all objects are tested and sorted.",
        easier="Adult names the objects; child guesses.",
        harder="Predict by material, then group the results.",
        recovery="A surprise result is a chance to wonder why together.",
        safety="Objects must be clean, unbreakable, and not sharp.",
    ),
    "act_one_move_puzzle": c(
        say="This puzzle is one move from solved. Take a good look, then tell me the single move.",
        setup="A set of arranged objects (coins, cups, tokens) where one change solves it.",
        steps="Set up the arrangement, let everyone inspect, then each player proposes the one move that fixes the pattern.",
        turns="Players take turns proposing; test each guess.",
        end="When the single move is found.",
        easier="Adult shows two candidate moves.",
        harder="Abstract the clue or add a time to think.",
        recovery="Give a gentle clue about which part is off.",
    ),
    "act_memory_tray": c(
        say="Look at everything on the tray for twenty seconds. Now I'll cover it — name what was there!",
        setup="A tray and 6–10 small household objects, plus a cloth to cover it.",
        steps="Study the tray, cover it, then recall as many objects as you can; add or remove one item each round to keep it fresh.",
        turns="Each player recalls in turn, cooperating to build the full list.",
        end="After everyone has recalled, or the list is complete.",
        easier="Fewer objects, longer look.",
        harder="Recall the exact order too.",
        coop="Team recall — combine what everyone remembers.",
        recovery="Cover and look again if the group wants a second glance.",
    ),
    "act_build_remix_teach": c(
        say="Build something small. Now change one rule about it. Finally, teach me how to build your version.",
        setup="Blocks, bricks, or simple craft materials.",
        steps="Build a small structure, change one rule (taller, only two colors, no base), then explain the method to the adult or a toy.",
        turns="Each person builds, remixes, and teaches once.",
        end="When each builder has taught their version.",
        easier="Adult builds first to model.",
        harder="Teach the build without touching the pieces.",
        coop="Teaching IS the goal — not building 'better.'",
        recovery="A wobbly build gets reconsidered and re-told.",
    ),
    "act_opposite_hand_drawing": c(
        say="Let's draw a simple picture — but with the hand you usually don't use.",
        setup="Paper and a pen or crayon.",
        steps="Draw something simple with your non-dominant hand, then compare how it feels and looks with a usual-hand version.",
        turns="Each person draws both versions.",
        end="When everyone has both drawings to compare.",
        easier="Draw a straight line or circle first.",
        harder="Write your name with the other hand.",
        recovery="Wobbly is expected and funny — that's the point.",
    ),
    "act_shape_detective": c(
        say="Find me a circle in this room. Now a triangle. Now a square — be our shape detective.",
        steps="Call a shape, and everyone hunts around the room for a real object containing it; take turns calling a shape.",
        turns="Each player gets to call one shape per round.",
        end="After everyone has called a shape, or the room is 'cleared.'",
        easier="Name simple shapes you can point at.",
        harder="Find two shapes in one object, or a shape only partly visible.",
        recovery="If a shape is hard, allow imaginary objects too.",
    ),
    "act_secret_rule": c(
        say="Some things can join my club and some can't. Guess my secret rule by trying things.",
        steps="The leader thinks of a hidden membership rule and says yes/no as people propose items; players deduce the rule.",
        turns="Each player proposes one item, then everyone can guess the rule.",
        end="When someone states the rule, or the leader reveals it after examples.",
        easier="A visible rule (red things, animals).",
        harder="A word-pattern or two-part rule.",
        recovery="If the rule has an accidental exception, accept it and repair the rule.",
    ),
}
