"""How-to-play cards for the 20 existing Move activities."""
def c(**kw):
    return {k: v for k, v in kw.items() if v}

CARDS = {
    "act_bus_stop_dance": c(
        say="'When the music stops, it's the bus stop — strike your silliest dancer pose and freeze!'",
        steps="Play one song; everyone dances, then freezes in a pose when the music pauses. Give each pose a name.",
        turns="Each round, one player picks the freeze pose theme.",
        end="After each willing player has led a pose, or a few songs.",
        easier="Adult calls the freeze first.",
        harder="Two players must pose together to make one scene.",
        coop="Dancing is for everyone — there's no 'best' or 'out.'",
        recovery="A wobble just means you invented a new pose.",
        safety="Clear the floor; no running in tight spaces.",
    ),
    "act_color_limb_callout": c(
        say="'Touch something blue with your elbow!' — you name a color and a body part, everyone finds that color to touch.",
        steps="One player calls a color and a limb; everyone moves to touch something of that color with that limb without falling.",
        turns="Each player gets to call one combination.",
        end="After everyone has called, or you run out of colors nearby.",
        easier="Name a color and let any body part count.",
        harder="Name two colors and two limbs at once.",
        recovery="If a color is missing, 'invent' it as a named imaginary spot.",
        safety="Face a clear path; no climbing or reaching over furniture.",
    ),
    "act_sock_knockdown": c(
        say="'Let's knock down these cup towers with rolled socks. The whole family gets six throws together.'",
        setup="Two rolled socks and three empty paper cups per tower.",
        steps="Set up cup targets, then take turns throwing the socks below shoulder height to knock them down.",
        turns="Players take turns throwing; everyone shares the same score as one team.",
        end="When all cups are down or the six throws are used.",
        easier="Set targets closer.",
        harder="Rebuild the cups in a taller stack between rounds.",
        coop="One shared team score — you win together.",
        recovery="A miss is just a set-up for the next throw.",
        safety="Throw below shoulder height, clear the floor, never aim at people.",
    ),
    "act_three_bottle_relay": c(
        say="'Let's fill these clean bottles and pass them in a relay — the goal is working together, not speed.'",
        setup="Three clean, empty, unbreakable bottles and a jug of water (adult pours).",
        steps="Fill and transfer the bottles along a little relay line, one person at a time, without spilling.",
        turns="Each player completes one transfer, then passes to the next.",
        end="When the jug is emptied into the bottles, or a set number of passes.",
        easier="Just two bottles and a small cup.",
        harder="Do the pass with one hand behind your back.",
        coop="A spill is a team chance to wipe up together.",
        recovery="Pause and rebalance instead of hurrying.",
        safety="Adult handles the water source; wipe spills.",
    ),
    "act_mirror_hands": c(
        say="Face me and copy my hands — move slowly so it looks exactly like a mirror.",
        steps="One player leads slow hand and face movements; the partner copies them like a mirror.",
        turns="Leader swaps after a few moves.",
        end="After everyone has led once.",
        easier="Copy only hands, not faces.",
        harder="Mirror at the same speed without a leader's cue.",
        coop="The goal is looking identical together, not competing.",
        recovery="If you lose sync, laugh and start a fresh slow move.",
        safety="Seated is fine; keep hands gentle.",
    ),
    "act_two_hand_dot": c(
        say="Draw a trail on paper, then try to follow it — a dot and a line — with both hands at once.",
        setup="Paper and two markers or crayons.",
        steps="Draw a simple dotted or wavy trail, then trace it simultaneously with one hand in each color.",
        turns="Each person draws a trail and then traces it.",
        end="After everyone has a completed trail.",
        easier="Trace a straight line with both hands.",
        harder="Do it faster, or with opposite hands.",
        recovery="Mismatched hands just make a wobbly, fun trail.",
    ),
    "act_listen_land": c(
        say="Listen for the signal — when you hear it, take one step or toss. Go!",
        steps="One player gives a clear audio cue; others land a step or a soft toss only when they hear it, tuning their listening.",
        turns="Rotate who gives the cues.",
        end="After eight signals or a couple rounds.",
        easier="A loud, slow signal.",
        harder="Two different signals for two different moves.",
        recovery="Repeat the signal once if it was missed — no penalty.",
        safety="Clear space; seated version for small rooms.",
    ),
    "act_home_obstacle_remix": c(
        say="'Let's build an obstacle course from pillows and chairs, then run it together.'",
        setup="Pillows, cushions, and safe chairs/flat surfaces.",
        steps="Build a short course together (over, under, around), then each person runs it; remix one element each round.",
        turns="Everyone runs the course; then the next builder remixes one piece.",
        end="After two or three remixed versions.",
        easier="A three-obstacle straight line.",
        harder="Add a 'carry a soft object' rule.",
        recovery="Rebuild any wobbly part before running it.",
        safety="Adult spots; no jumping off furniture; clear breakables.",
    ),
    "act_one_minute_juggle": c(
        say="Let's practice a one-minute juggling path with scarves — there's no mastery goal, just trying.",
        setup="Two or three light scarves or cloths.",
        steps="Toss one scarf hand to hand, then add a second, following a simple figure-eight path; keep it slow.",
        turns="Each person practices their own path and can take a turn to teach it.",
        end="After a few minutes or when you've kept two going.",
        easier="One scarf, big slow arcs.",
        harder="Three scarves, or catch with the opposite hand.",
        recovery="A drop is a reset, not a failure.",
        safety="Clear space; scarves, nothing hard.",
    ),
    "act_slow_motion_leader": c(
        say="Let's move in slow motion. I'll lead; copy me as slowly as you can.",
        steps="One player leads big, slow, exaggerated movements; everyone mirrors at the same unhurried pace.",
        turns="Swap leader each round.",
        end="After everyone has led once.",
        easier="Small hand movements only.",
        harder="The whole body, one sense at a time.",
        coop="Staying slow together is the win.",
        recovery="If someone speeds up, everyone gently slows back down.",
        safety="Works seated or standing in open space.",
    ),
    "act_rhythm_copycat": c(
        say="Clap this pattern — copy it back, then make one of your own.",
        steps="One player claps or taps a short rhythm; the next copies it, then invents a new one.",
        turns="Each player copies then leads.",
        end="After everyone has led one pattern.",
        easier="Two-beat patterns.",
        harder="Add a foot tap or a pause.",
        coop="You're building a joint rhythm, not testing memory.",
        recovery="The group can clap along to help rebuild a pattern.",
    ),
    "act_floor_pattern": c(
        say="'Let's make a moving pattern: hop, step, spin — then cross the floor doing it.'",
        steps="Agree on a 3–4 move pattern, practice it, then move across the floor following it together.",
        turns="Each player proposes one move for the pattern.",
        end="After two full crossings or a set time.",
        easier="Two moves, a straight line.",
        harder="Do the pattern backward.",
        coop="Everyone learns and performs the same pattern.",
        safety="Clear floor; no running or spinning near furniture.",
    ),
    "act_cup_transfer": c(
        say="'Let's pass these cups down the line without dropping them — go slow.'",
        setup="Several unbreakable cups or small bowls.",
        steps="Line up and pass the cups from person to person, one at a time, talking through each handoff.",
        turns="A cup travels through everyone; swap order each round.",
        end="After all cups make the full trip.",
        easier="Pass one cup slowly.",
        harder="Pass while walking and talking.",
        coop="A dropped cup is a team 'pick it back up together.'",
        recovery="Pause, pick up, and pass — nobody is out.",
    ),
    "act_back_to_back_stand": c(
        say="'Sit back-to-back with me, link arms, and let's stand up together without using our hands.'",
        steps="Two players sit back-to-back, hook arms mildly, and push against each other to stand.",
        turns="Every player gets a partner and a turn.",
        end="When everyone has stood together at least once.",
        easier="Sit closer on the floor.",
        harder="Do it with three people forming a triangle.",
        coop="You literally rise together.",
        recovery="Start from a chair if the floor is hard.",
        safety="Soft surface; adult pairs with the youngest.",
    ),
    "act_animal_movement_chain": c(
        say="Move across the room like a bear, then a bunny, then a crab — string them into one chain.",
        steps="Each player names an animal and demonstrates its movement; then the group chains them, moving like each in turn.",
        turns="Each player contributes one animal move.",
        end="After one full chain or everyone has led.",
        easier="Copy a single animal the adult shows.",
        harder="Chain three animals without repeating.",
        coop="The chain is shared — help each other remember the order.",
        recovery="Forget the order? Everyone just does the bunny hop again.",
        safety="Big, clear space; no leaps or jumps.",
    ),
    "act_freeze_explain": c(
        say="'Freeze in a pose — now tell us what you're pretending to be!'",
        steps="One player freezes mid-move; everyone else guesses the pose or the player explains it.",
        turns="Each player gets to freeze once.",
        end="After everyone has frozen.",
        easier="Freeze into a simple named shape.",
        harder="Two players freeze into one connected scene.",
        coop="Guesses are fun ideas, not right/wrong answers.",
        recovery="If nobody guesses, the frozen player gives a one-word clue.",
    ),
    "act_hallway_curling": c(
        say="'Let's slide soft pucks to the hallway target and see who lands closest — gentle throws only.'",
        setup="Soft pucks or rolled socks and a clear hallway target line.",
        steps="Slide the soft puck toward a target, taking turns; measure who lands closest with steady paces.",
        turns="Each player slides once per round.",
        end="After a few rounds or a set score.",
        easier="A bigger target.",
        harder="Add a small 'gate' the puck must pass through.",
        coop="Cheer every landing; no elimination.",
        recovery="A wide miss is a chance for someone else's close call.",
        safety="Only soft, safe objects; clear the lane.",
    ),
    "act_grandparent_move_teach": c(
        say="Grandparent, what's a move or dance from when you were young? Teach it to us and we'll mirror it.",
        steps="A grandparent (nearby or on video) demonstrates an old dance or everyday move; the family copies it and practices together.",
        turns="The grandparent teaches; everyone mirrors; then family members teach a move back.",
        end="When the family can do the move together a few times.",
        easier="Copy a simple gesture.",
        harder="Chain the grandparent's move into the family's own mini-routine.",
        coop="Learning a shared move connects generations.",
        recovery="Everyone moves at the comfort of the oldest player.",
        safety="Seated or gentle versions as needed; stop on any discomfort.",
    ),
    "act_seated_balloon_keepup": c(
        say="Let's keep this balloon off the ground — from our chairs! Tap it, don't swing.",
        setup="One inflated balloon.",
        steps="While seated, tap the balloon to keep it up together; count your longest streak.",
        turns="Anyone can tap; it's a team streak.",
        end="After a set streak or time.",
        easier="Use slow, gentle taps.",
        harder="Each tap must be with only one hand.",
        coop="It's one shared streak, so you win together.",
        recovery="When it drops, start counting again — no blame.",
        safety="Adult inflates; supervise balloon fragments (latex).",
    ),
    "act_movement_dice": c(
        say="'Let's roll our movement cube — whatever it shows, we all do. Ready?'",
        setup="A cube you label with six movements (jump, spin, stomp, wiggle, clap, stretch).",
        steps="Roll the cube, read the movement, and everyone performs it together; you can agree to do it 'big' or 'tiny.'",
        turns="Each player takes a turn rolling.",
        end="After everyone has rolled twice.",
        easier="Only safe, gentle movements on the cube.",
        harder="Combine the last two rolled moves.",
        coop="Everyone does every roll together.",
        recovery="Whatever lands, adapt to your space (tiny jumps if room is small).",
        safety="Label the cube with only space-safe moves.",
    ),
}
