"""How-to-play cards for the 20 existing Make activities."""
def c(**kw):
    return {k: v for k, v in kw.items() if v}

CARDS = {
    "act_shadow_doubles": c(
        say="Let's catch a shadow. Put something where the sun makes a clear outline, and we'll trace what it becomes.",
        setup="Paper, a pencil or crayon, and a sunny spot or bright lamp.",
        steps="One person holds an object still; the other traces its shadow. Then invent details to turn the outline into a character or scene.",
        turns="Swap who holds and who traces each round.",
        end="Finish when each player has traced one shadow-double and named it.",
        easier="Trace your own hand shadow.",
        harder="Combine two objects' shadows into one creature.",
        coop="Work as one team — tracing together is the fun, not competition.",
        recovery="If the shadow is unclear, move the light or use a bigger object.",
        safety="Never stare into bright lights; use a lamp, not the sun, indoors.",
    ),
    "act_wiggly_snake": c(
        say="'Let's fold a paper snake that wiggles when you pull the bottom strip.'",
        setup="A long paper strip, scissors, and markers.",
        steps="Fold the strip back and forth like an accordion, draw a snake head, then pull the tail to make it wiggle.",
        turns="Each person makes their own snake, then hold a gentle 'wiggle-off.'",
        end="After everyone has one wiggling snake.",
        easier="Adult pre-folds; the child draws the face.",
        harder="Give the snake a pattern that repeats correctly.",
        child="Let the child choose the colors and the snake's name and personality.",
        safety="Scissors used by the adult or with supervision.",
    ),
    "act_tissue_bunny": c(
        say="'Let's twist a tissue into a little animal — a bunny, a mouse, a bear.'",
        setup="A few tissues or paper napkins and a marker (optional).",
        steps="Roll and twist the tissue into a body, add a head and ears, and draw a tiny face.",
        turns="Each person makes one creature, then introduce them to each other.",
        end="When every creature has a name.",
        easier="Adult does the twist, child adds the face.",
        harder="Make the creature do a simple pose.",
        child="Let the child decide what animal it becomes.",
    ),
    "act_paper_claw": c(
        say="'Let's fold paper claws to wear — then play a gentle creature game with them.'",
        setup="Square paper sheets (one per claw) and tape.",
        steps="Fold each sheet into a cone-shaped claw you can slip onto your fingers, then tape them.",
        turns="Wear them and take turns being the 'gentle monster' chasing softly.",
        easier="Adult folds; child decorates.",
        harder="Add a pattern or color to make them look real.",
        recovery="If a fold goes wrong, unfold and restart together.",
        safety="Claws stay blunt and are never aimed at faces or used hard.",
    ),
    "act_returning_disk": c(
        say="'Let's make a paper disk that curves and comes back toward you.'",
        setup="Cardstock or stiff paper, scissors, and an open, clear space.",
        steps="Cut a disk shape, add the fold and tilt from the guide, then throw gently to see it curve.",
        turns="Test throws in turn; nobody scores — you're figuring it out together.",
        end="When the disk flies a satisfying arc a few times in a row.",
        easier="Adult cuts; child throws.",
        harder="Try different tilts and note which returns best.",
        recovery="If it won't return, adjust the tilt rather than throwing harder.",
        safety="Throw only in a clear indoor space away from faces and breakables.",
    ),
    "act_cross_boomerang": c(
        say="'Let's fold a cross-shaped flier and see if it comes back.'",
        setup="Stiff paper or cardstock and scissors.",
        steps="Cut and fold a cross shape, follow the wing-tilt guide, and test its flight in a clear space.",
        turns="Each person tests and tweaks their own.",
        end="When each player has seen it fly (not necessarily return).",
        easier="Adult handles cutting.",
        harder="Add weight with a paper clip and note the difference.",
        recovery="Tweak the angles gently; never throw harder to 'fix' it.",
        safety="Fly in open space only, never toward people or windows.",
    ),
    "act_jumping_balloon": c(
        say="'Let's build a balloon toy that jumps. An adult will handle the balloon.'",
        setup="A balloon, rubber band or ring, and a safe open floor.",
        steps="Follow the demonstration to connect a balloon so it jumps when released; adult inflates and handles small parts.",
        turns="The child presses the trigger; the adult sets it up.",
        end="After a few jumps, put the balloon away intact.",
        recovery="If it won't jump, check the band tension together.",
        safety="Adult-led — latex allergy first, and never blow into broken pieces; discard fragments safely.",
    ),
    "act_found_flower_frame": c(
        say="'Let's find safe fallen flowers and leaves and press them into a picture frame.'",
        setup="Paper, a frame or card, and clear tape or glue.",
        steps="Collect only fallen, already-on-the-ground flowers and leaves, arrange them in the frame, and tape them down.",
        turns="Each person arranges one section or one flower.",
        end="When the frame is finished and hung or given away.",
        easier="Adult handles the glue.",
        harder="Arrange by color gradient.",
        child="Let the child choose the composition.",
        safety="Pick up only fallen plants — never pull living ones or handle unknown berries.",
    ),
    "act_secret_gift_wrap": c(
        say="'Let's wrap this gift with a fun reveal — maybe a hidden note or a surprise on the inside.'",
        setup="Wrapping paper or newspaper, tape, scissors, and a small gift.",
        steps="Wrap the gift, then add a clever detail: a hidden note, a 'do not open until' tag, or a playful pattern.",
        turns="One person measures and cuts, one tapes and decorates.",
        end="When the gift is wrapped and the recipient is happy.",
        easier="Adult does folds; child adds stickers and the tag.",
        harder="Add a riddle on the tag that points to the gift.",
        coop="Wrap as a team — this is a gift, not a race.",
        safety="Adult handles scissors.",
    ),
    "act_blow_paper_creature": c(
        say="'Let's make a paper creature we can move by blowing through our own straw.'",
        setup="Paper, a straw (your own), and scissors.",
        steps="Fold a lightweight paper creature with a tab you can push, then move it by blowing gently through your own straw.",
        turns="Each person moves their own creature; nobody shares straws.",
        end="After a short 'blow race' or once the creature works.",
        easier="Adult cuts the shape.",
        harder="Design a creature that moves two ways.",
        recovery="Blow more gently and aim at the tab, not the creature's head.",
        safety="Each child uses their own straw; no blowing at faces or food.",
    ),
    "act_color_collage_walk": c(
        say="'Let's go on a color walk and collect safe bits, then arrange them into a collage.'",
        setup="A bag or box, paper, and glue (optional).",
        steps="Walk nearby and collect only safe, already-on-the-ground items in chosen colors, then arrange them into a color collage.",
        turns="Each person claims a color to collect.",
        end="When the collage is complete or the walk ends.",
        easier="Collect just leaves in two colors.",
        harder="Sort by shade from light to dark.",
        recovery="Collected items can be rearranged until everyone likes the layout.",
        safety="Only safe, clean, non-sharp finds; wash hands after.",
    ),
    "act_one_sheet_bunny": c(
        say="'Let's fold one sheet of paper into a standing bunny.'",
        setup="One square sheet of paper per person.",
        steps="Follow a simple fold sequence to make a bunny that stands; draw a face when done.",
        turns="Each person folds their own, helping each other.",
        end="When every bunny stands.",
        easier="Adult folds; child adds features.",
        harder="Add a pocket to the bunny.",
        recovery="Refold any step slowly together — no rush.",
    ),
    "act_bat_fold": c(
        say="'Let's fold a paper bat and flutter it around a clear space.'",
        setup="A square paper sheet and scissors.",
        steps="Fold the bat shape, then flutter it with a gentle flick.",
        turns="Each person makes and flies their own bat.",
        end="After everyone has made one and flown it.",
        easier="Adult pre-folds wings.",
        harder="Make the bat clasp around a finger.",
        recovery="Unfold and refold rather than restarting.",
        safety="Fly it in open space, away from faces and fans.",
    ),
    "act_family_flag": c(
        say="'Let's design a flag that shows who our family is — colors, a symbol, and a motto.'",
        setup="Paper or fabric, and markers, crayons, or paint.",
        steps="Talk about what represents your family, then draw a flag with a color, symbol, and short motto together.",
        turns="Each person proposes one element; the family votes.",
        end="When the flag is finished and given a name.",
        easier="Adult draws the outline; child fills color.",
        harder="Fold or fringe the edges so it hangs like a real flag.",
        coop="Decisions are made together — no majority 'wins' over another.",
    ),
    "act_cardboard_marble": c(
        say="'Let's build a marble run from cardboard and tape, then test and improve it.'",
        setup="Cardboard strips, tape, scissors, and a small marble or ball.",
        steps="Design and attach ramps and lanes so a marble rolls top to bottom; test, then change one thing to improve it.",
        turns="Each person adds one section of track.",
        end="When the marble makes it all the way a few times.",
        easier="Adult builds a starter ramp; child adds a drop.",
        harder="Add a jump or a curved funnel.",
        recovery="A stuck marble is a clue — spot where it stops and adjust there.",
        safety="Adult handles cutting; keep the marble away from mouths (small parts).",
    ),
    "act_sock_puppet": c(
        say="'Let's make a sock puppet and have it interview a family member.'",
        setup="A clean sock, markers or googly eyes, and small decorations.",
        steps="Slip the sock on a hand, draw or add a face, and give the puppet a voice; then it interviews a family member.",
        turns="Each person gets to be the puppeteer once.",
        end="When each puppet has interviewed someone.",
        easier="Adult makes the puppet; child gives it a voice.",
        harder="The puppet must use one new word everyone taught it.",
        child="The child names the puppet and its personality.",
    ),
    "act_fold_fly_lab": c(
        say="'Let's fold a few paper planes and run a tiny flight experiment — predict, then test, then change.'",
        setup="Paper sheets and a clear throwing space.",
        steps="Fold two different planes, predict which will fly farther, throw each gently, and measure, then tweak one design.",
        turns="Each person throws their own; everyone writes the 'findings.'",
        end="After you've tested three designs or two rounds.",
        easier="Adult folds; child throws and measures (with steps).",
        harder="Add a paper clip and compare flight.",
        recovery="If a plane dives, re-fold the nose — don't throw harder.",
        safety="Throw gently in open space, never at people.",
    ),
    "act_paper_chain_machine": c(
        say="'Let's become a paper-chain machine and build the longest chain we can as a team.'",
        setup="Paper strips, glue or tape.",
        steps="Loop each strip into a link and connect them into a chain; work side by side on the same chain.",
        turns="Each person adds a link, in any order, as one team.",
        end="When the chain is as long as the room, or after a set time.",
        easier="Adult pre-cuts strips.",
        harder="Build a second chain and join both at the end.",
        coop="This is a shared chain — everyone's links count toward one goal.",
        recovery="A broken link just gets retaped; nobody restarts.",
    ),
    "act_nature_crown": c(
        say="'Let's weave a crown from safe, found natural bits.'",
        setup="Fallen leaves, soft stems or grass, and a paper band (optional).",
        steps="Collect safe fallen materials, then attach them around a band or loop to make a crown.",
        turns="Each person adds their collected pieces to the crown.",
        end="When the crown fits and looks finished.",
        easier="Adult builds the base; child tucks in leaves.",
        harder="Weave in a repeating pattern of colors.",
        child="The child decides whose crown it becomes — or everyone makes one.",
        safety="Use only fallen, clean plant material; no unknown or thorny bits.",
    ),
    "act_toy_shadow_city": c(
        say="'Let's line up our toys by a light and build a whole city out of their shadows.'",
        setup="Toys, a lamp or flashlight, and a plain wall or floor.",
        steps="Arrange toys near the light so their shadows overlap into buildings and streets; tell a tiny city story.",
        turns="Each person adds a 'building' or a character.",
        end="When the city has a story and a name.",
        easier="Adult holds the light steady.",
        harder="Move the light to change the city at different times of day.",
        child="The child decides what happens in the city.",
        recovery="If shadows blur, move a toy or the light.",
    ),
}
